// @vitest-environment happy-dom
import type { AvailabilityWorkspaceProjection } from "@adminbot/api-contracts";
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { AvailabilityClient } from "./availability-api-client.js";
import { AdminBotAvailabilityWorkspace } from "./availability-workspace.js";

if(!customElements.get("adminbot-availability-workspace"))customElements.define("adminbot-availability-workspace",AdminBotAvailabilityWorkspace);
const PERSON="20000000-0000-4000-8000-000000000001";const PEER="20000000-0000-4000-8000-000000000002";const PLAN="30000000-0000-4000-8000-000000000001";
const workspace:AvailabilityWorkspaceProjection={viewerPersonId:PERSON,viewerRoles:["member"],asOf:"2026-08-08T12:00:00Z",ownPlan:plan(),visiblePlans:[plan(),plan({id:"30000000-0000-4000-8000-000000000002",personId:PEER,personName:"Peer Member",entries:[]})],summaries:[{personId:PERSON,personName:"Member One",allocatedHours:20,openHours:5,away:"none",confirmedAt:"2026-08-08T12:00:00Z",stale:false},{personId:PEER,personName:"Peer Member",allocatedHours:30,openHours:0,away:"partial",stale:true}]};
describe("availability workspace",()=>{beforeEach(()=>document.body.replaceChildren());it("renders member selection, interval chart, and current summary",async()=>{const element=create();document.body.append(element);await vi.waitFor(()=>expect(element.shadowRoot?.textContent).toContain("Member One"));expect(element.shadowRoot?.querySelector('[aria-label="Availability allocation chart"]')).not.toBeNull();expect(element.shadowRoot?.textContent).toContain("20h");const member=element.shadowRoot?.querySelector<HTMLSelectElement>(".controls select");if(!member)throw new Error("member selector missing");member.value=PEER;member.dispatchEvent(new Event("change"));await element.updateComplete;expect(element.shadowRoot?.textContent).toContain("Peer Member");expect(element.shadowRoot?.textContent).toContain("Partialtime off");});it("deletes a manual row and saves the version-checked plan",async()=>{const client=fake();const element=create(client);document.body.append(element);await vi.waitFor(()=>expect(element.shadowRoot?.querySelector("button.danger")).not.toBeNull());element.shadowRoot?.querySelector<HTMLButtonElement>("button.danger")?.click();element.shadowRoot?.querySelector<HTMLButtonElement>("button.primary:not([type=submit])")?.click();await vi.waitFor(()=>expect(client.replace).toHaveBeenCalled());expect(client.replace).toHaveBeenCalledWith(expect.objectContaining({planId:PLAN,expectedVersion:1,entries:[]}));});});
function create(client=fake()){const element=document.createElement("adminbot-availability-workspace") as AdminBotAvailabilityWorkspace;element.client=client;return element;}
function fake():AvailabilityClient&{replace:ReturnType<typeof vi.fn>}{return{get:vi.fn().mockResolvedValue(workspace),replace:vi.fn().mockResolvedValue({...workspace,ownPlan:{...workspace.ownPlan,entries:[],version:2}})}};
function plan(overrides:Partial<AvailabilityWorkspaceProjection["ownPlan"]>={}):AvailabilityWorkspaceProjection["ownPlan"]{return{id:PLAN,organizationId:"10000000-0000-4000-8000-000000000001",personId:PERSON,personName:"Member One",timeZone:"Europe/London",defaultWeeklyHours:40,entries:[{id:"40000000-0000-4000-8000-000000000001",kind:"allocation",startsOn:"2026-08-01",endsOn:"2026-09-01",hoursPerWeek:20,label:"Research",color:"#3575da",visibility:"members",source:"manual",confirmedAt:"2026-08-08T12:00:00Z"}],version:1,createdAt:"2026-08-01T00:00:00Z",updatedAt:"2026-08-08T12:00:00Z",...overrides};}
