import { css, html, LitElement, nothing, type TemplateResult } from "lit";
import type { AvailabilityEntry, AvailabilityPlan, AvailabilitySummary, AvailabilityWorkspaceProjection } from "@adminbot/api-contracts";
import { AvailabilityApiClient, AvailabilityApiError, type AvailabilityClient } from "./availability-api-client.js";

type Interval = "day" | "week" | "month";
const COLORS = ["#3575da", "#00676e", "#f6511d", "#188b3e", "#8b5cf6", "#d4a72c"] as const;
const DAY = 86_400_000;

export class AdminBotAvailabilityWorkspace extends LitElement {
  static override properties = { workspace: { state: true }, loading: { state: true }, error: { state: true }, notice: { state: true }, selectedPersonId: { state: true }, interval: { state: true }, windowStart: { state: true }, draftEntries: { state: true }, draftTimeZone: { state: true }, draftCapacity: { state: true }, saving: { state: true } };
  static override styles = css`
    :host { display:block; color:var(--text); } * { box-sizing:border-box; } h1 { margin:0; color:var(--text-strong); font:500 clamp(2rem,5vw,3.5rem)/1.05 Georgia,serif; } h2,h3 { color:var(--text-strong); } .eyebrow { color:var(--accent); font-size:.65rem; font-weight:780; letter-spacing:.14em; text-transform:uppercase; } .lede { max-width:54rem; color:var(--text-muted); line-height:1.6; }
    button,input,select { font:inherit; } button { border:1px solid var(--border-strong); border-radius:.55rem; padding:.55rem .7rem; color:var(--text); background:var(--surface-3); cursor:pointer; } button.primary { border-color:var(--accent); color:var(--accent-ink); background:var(--accent); font-weight:750; } button.danger { color:var(--danger); } button:disabled { opacity:.5; cursor:wait; } input,select { width:100%; border:1px solid var(--border-strong); border-radius:.55rem; padding:.56rem .62rem; color:var(--text-strong); background:var(--surface-1); }
    .controls,.settings { display:grid; grid-template-columns:repeat(3,minmax(10rem,1fr)); gap:.7rem; margin:1rem 0; } label { display:grid; gap:.3rem; color:var(--text-muted); font-size:.7rem; } .card { margin-top:1rem; border:1px solid var(--border); border-radius:.85rem; padding:1rem; background:var(--surface-2); } .status { border-left:.2rem solid var(--accent); padding:.65rem .8rem; background:var(--accent-soft); } .status.error { border-color:var(--danger); color:var(--danger); }
    .summary { display:grid; grid-template-columns:repeat(4,1fr); gap:.6rem; } .metric { border:1px solid var(--border); border-radius:.7rem; padding:.7rem; background:var(--surface-1); } .metric strong { display:block; color:var(--text-strong); font-size:1.25rem; } .metric small { color:var(--text-muted); }
    .pager { display:flex; align-items:center; justify-content:space-between; gap:.6rem; margin:.8rem 0; } .chart { display:grid; grid-template-columns:repeat(7,minmax(5.5rem,1fr)); gap:.4rem; overflow:auto; padding-bottom:.4rem; } .bucket { min-width:5.5rem; } .bucket > small { display:block; min-height:2rem; color:var(--text-muted); font-size:.62rem; } .stack { position:relative; display:flex; flex-direction:column-reverse; height:12rem; overflow:hidden; border:1px solid var(--border); border-radius:.55rem; background:linear-gradient(to top,transparent 49.5%,var(--border) 50%,transparent 50.5%); } .stack.over { border-color:var(--danger); box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--danger) 35%,transparent); } .segment { min-height:.2rem; color:white; font-size:.56rem; padding:.15rem; overflow:hidden; } .away { position:absolute; inset:0; display:grid; place-items:center; color:var(--text-strong); background:color-mix(in srgb,var(--surface-1) 82%,transparent); font-weight:750; } .capacity { position:absolute; left:0; right:0; bottom:99%; border-top:1px dashed var(--danger); }
    .legend { display:flex; flex-wrap:wrap; gap:.6rem; margin:.6rem 0; color:var(--text-muted); font-size:.68rem; } .legend i { display:inline-block; width:.65rem; height:.65rem; margin-right:.25rem; border-radius:.15rem; }
    .table-wrap { overflow:auto; } table { width:100%; border-collapse:collapse; min-width:68rem; } th,td { padding:.45rem; border-bottom:1px solid var(--border); text-align:left; vertical-align:top; } th { color:var(--text-muted); font-size:.63rem; text-transform:uppercase; } td input,td select { min-width:7rem; } .row-note { max-width:14rem; color:var(--text-muted); font-size:.66rem; } .add-form { display:grid; grid-template-columns:1.2fr 1.4fr repeat(2,1fr) .8fr auto; gap:.55rem; align-items:end; margin-top:1rem; } .actions { display:flex; justify-content:flex-end; gap:.5rem; margin-top:1rem; } .empty { padding:2rem; color:var(--text-muted); text-align:center; }
    @media(max-width:850px){ .controls,.settings,.summary { grid-template-columns:repeat(2,1fr); } .add-form { grid-template-columns:repeat(2,1fr); } } @media(max-width:560px){ .controls,.settings,.summary,.add-form { grid-template-columns:1fr; } }
  `;
  client: AvailabilityClient = new AvailabilityApiClient(import.meta.env.VITE_ADMINBOT_API_ORIGIN || window.location.origin);
  declare private workspace: AvailabilityWorkspaceProjection | undefined; declare private loading:boolean; declare private error:string; declare private notice:string; declare private selectedPersonId:string; declare private interval:Interval; declare private windowStart:string; declare private draftEntries:AvailabilityEntry[]; declare private draftTimeZone:string; declare private draftCapacity:number; declare private saving:boolean;
  constructor(){ super(); this.loading=true; this.error=""; this.notice=""; this.selectedPersonId=""; this.interval="week"; this.windowStart=align(today(),"week"); this.draftEntries=[]; this.draftTimeZone="UTC"; this.draftCapacity=40; this.saving=false; }
  override connectedCallback():void { super.connectedCallback(); void this.load(); }
  override render():TemplateResult { if(this.loading) return html`<div class="empty">Loading availability…</div>`; const plan=this.selectedPlan; const summary=this.selectedSummary; return html`
    <header><p class="eyebrow">Capacity · member-owned planning</p><h1>Time availability</h1><p class="lede">Plan allocations, explicitly declared open capacity, tentative work, and time off. Time off overrides capacity totals; private reasons remain visible only to you and administrators.</p></header>
    ${this.notice?html`<p class="status" role="status">${this.notice}</p>`:nothing}${this.error?html`<p class="status error" role="alert">${this.error}</p>`:nothing}
    <div class="controls"><label>Member<select .value=${this.selectedPersonId} @change=${(e:Event)=>{this.selectedPersonId=(e.target as HTMLSelectElement).value;}}>${this.workspace?.summaries.map((s)=>html`<option value=${s.personId}>${s.personName}</option>`)}</select></label><label>Chart interval<select .value=${this.interval} @change=${(e:Event)=>{this.interval=(e.target as HTMLSelectElement).value as Interval;this.windowStart=align(this.windowStart,this.interval);}}><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option></select></label><label>Snapshot<input readonly .value=${new Date(this.workspace?.asOf ?? "").toLocaleString()} /></label></div>
    ${summary?this.renderSummary(summary):nothing}${plan?this.renderPlan(plan):html`<div class="empty">No visible availability plan.</div>`}
  `; }
  private renderSummary(summary:AvailabilitySummary):TemplateResult { return html`<section class="summary" aria-label="Current availability summary"><div class="metric"><strong>${summary.allocatedHours}h</strong><small>allocated now</small></div><div class="metric"><strong>${summary.openHours}h</strong><small>declared open</small></div><div class="metric"><strong>${friendly(summary.away)}</strong><small>time off</small></div><div class="metric"><strong>${summary.stale?"Review":"Current"}</strong><small>${summary.confirmedAt?`confirmed ${new Date(summary.confirmedAt).toLocaleDateString()}`:"never confirmed"}</small></div></section>`; }
  private renderPlan(plan:AvailabilityPlan):TemplateResult { const own=plan.personId===this.workspace?.viewerPersonId; const entries=own?this.draftEntries:plan.entries; return html`<section class="card"><div class="pager"><button @click=${()=>this.shift(-7)}>← Previous 7</button><div><h2>${plan.personName}</h2><small>${plan.defaultWeeklyHours}h weekly capacity · ${plan.timeZone}</small></div><button @click=${()=>this.shift(7)}>Next 7 →</button></div>${this.renderChart(entries,plan.defaultWeeklyHours)}${own?this.renderEditor():this.renderReadOnly(entries)}</section>`; }
  private renderChart(entries:readonly AvailabilityEntry[],capacity:number):TemplateResult { const buckets=Array.from({length:7},(_,i)=>bucket(this.windowStart,this.interval,i)); const visible=entries.filter(e=>e.kind!=="time_off"); const color=(entry:AvailabilityEntry)=>entry.color??COLORS[Math.max(0,visible.findIndex(candidate=>candidate.id===entry.id))%COLORS.length]; return html`<div class="legend">${visible.map((e)=>html`<span><i style=${`background:${color(e)}`}></i>${e.label||friendly(e.kind)}</span>`)}</div><div class="chart" role="img" aria-label="Availability allocation chart">${buckets.map((b)=>{const active=entries.filter(e=>overlaps(e,b));const allocated=active.filter(e=>e.kind!=="time_off");const away=active.filter(e=>e.kind==="time_off");const percent=allocated.reduce((sum,e)=>sum+(e.hoursPerWeek??0),0)/capacity*100;return html`<div class="bucket"><small>${b.label} · ${Math.round(percent)}%</small><div class=${`stack ${percent>100?"over":""}`}><span class="capacity"></span>${allocated.map((e)=>html`<span class="segment" style=${`height:${Math.max(3,((e.hoursPerWeek??0)/capacity)*100)}%;background:${color(e)}`} title=${`${e.label||friendly(e.kind)} ${e.hoursPerWeek??0}h`}>${e.hoursPerWeek??0}h</span>`)}${away.length?html`<span class="away">${away.some(e=>e.timeOffAvailability==="none")?"Away":"Partly away"}</span>`:nothing}</div></div>`;})}</div>`; }
  private renderReadOnly(entries:readonly AvailabilityEntry[]):TemplateResult { return html`<div class="table-wrap"><table><thead><tr><th>Type</th><th>Label</th><th>Dates</th><th>Hours</th><th>Visibility</th></tr></thead><tbody>${entries.map(e=>html`<tr><td>${friendly(e.kind)}</td><td>${e.label??"—"}${e.supportingUri?html` <a href=${e.supportingUri} target="_blank" rel="noopener noreferrer">source</a>`:nothing}</td><td>${e.startsOn} – ${e.endsOn}</td><td>${e.hoursPerWeek??"—"}</td><td>${friendly(e.visibility)}</td></tr>`)}</tbody></table></div>`; }
  private renderEditor():TemplateResult { return html`<div class="settings"><label>Weekly capacity<input type="number" min="1" max="168" .value=${String(this.draftCapacity)} @input=${(e:Event)=>{this.draftCapacity=Number((e.target as HTMLInputElement).value);}} /></label><label>Time zone<input .value=${this.draftTimeZone} @input=${(e:Event)=>{this.draftTimeZone=(e.target as HTMLInputElement).value;}} /></label><label>Plan version<input readonly .value=${String(this.workspace?.ownPlan.version??1)} /></label></div><div class="table-wrap"><table><thead><tr><th>Type</th><th>Label / reason</th><th>Start</th><th>End</th><th>Hours / away</th><th>Visibility</th><th></th></tr></thead><tbody>${this.draftEntries.map((e,i)=>this.renderEntry(e,i))}</tbody></table></div>${this.renderAddForm()}<div class="actions"><button class="primary" ?disabled=${this.saving} @click=${this.save}>${this.saving?"Saving…":"Save availability"}</button></div>`; }
  private renderEntry(entry:AvailabilityEntry,index:number):TemplateResult { const imported=entry.source==="imported"; return html`<tr><td><select ?disabled=${imported} .value=${entry.kind} @change=${(e:Event)=>this.change(index,"kind",(e.target as HTMLSelectElement).value)}>${kinds().map(k=>html`<option value=${k}>${friendly(k)}</option>`)}</select>${imported?html`<small class="row-note">Imported rows require reconciliation.</small>`:nothing}</td><td><input ?disabled=${imported} .value=${entry.kind==="time_off"?entry.privateReason??"":entry.label??""} @input=${(e:Event)=>this.change(index,entry.kind==="time_off"?"privateReason":"label",(e.target as HTMLInputElement).value)} />${entry.kind==="time_off"?nothing:html`<input aria-label="Row color" ?disabled=${imported} type="color" .value=${entry.color??COLORS[index%COLORS.length]} @input=${(e:Event)=>this.change(index,"color",(e.target as HTMLInputElement).value)} />`}<input aria-label="Supporting link" ?disabled=${imported} type="url" placeholder="Supporting link" .value=${entry.supportingUri??""} @input=${(e:Event)=>this.change(index,"supportingUri",(e.target as HTMLInputElement).value||undefined)} /></td><td><input ?disabled=${imported} type="date" .value=${entry.startsOn} @input=${(e:Event)=>this.change(index,"startsOn",(e.target as HTMLInputElement).value)} /></td><td><input ?disabled=${imported} type="date" .value=${entry.endsOn} @input=${(e:Event)=>this.change(index,"endsOn",(e.target as HTMLInputElement).value)} /></td><td>${entry.kind==="time_off"?html`<select ?disabled=${imported} .value=${entry.timeOffAvailability??"none"} @change=${(e:Event)=>this.change(index,"timeOffAvailability",(e.target as HTMLSelectElement).value)}><option value="none">Fully away</option><option value="partial">Partly away</option></select>`:html`<input ?disabled=${imported} type="number" min="0" max="168" .value=${String(entry.hoursPerWeek??0)} @input=${(e:Event)=>this.change(index,"hoursPerWeek",Number((e.target as HTMLInputElement).value))} />`}</td><td><select ?disabled=${imported} .value=${entry.visibility} @change=${(e:Event)=>this.change(index,"visibility",(e.target as HTMLSelectElement).value)}><option value="members">Members</option><option value="summary_only">Summary only</option><option value="administrators">Administrators</option></select></td><td><button class="danger" ?disabled=${imported} @click=${()=>{this.draftEntries=this.draftEntries.filter((_,n)=>n!==index);}}>Delete</button></td></tr>`; }
  private renderAddForm():TemplateResult { return html`<form class="add-form" @submit=${this.addEntry}><label>Type<select name="kind">${kinds().map(k=>html`<option value=${k}>${friendly(k)}</option>`)}</select></label><label>Label / private reason<input name="label" maxlength="200" /></label><label>Start<input name="start" type="date" required /></label><label>End<input name="end" type="date" required /></label><label>Hours<input name="hours" type="number" min="0" max="168" value="4" /></label><label>Supporting link<input name="link" type="url" /></label><button class="primary" type="submit">Add row</button></form>`; }
  private readonly addEntry=(event:SubmitEvent):void=>{event.preventDefault();const form=event.currentTarget as HTMLFormElement;const d=new FormData(form);const kind=String(d.get("kind")) as AvailabilityEntry["kind"];const label=String(d.get("label")??"").trim();const link=String(d.get("link")??"").trim();const start=String(d.get("start")??"");const end=String(d.get("end")??"");if(!start||!end||start>end){this.error="Choose a valid date range.";return;}this.error="";this.draftEntries=[...this.draftEntries,{id:crypto.randomUUID(),kind,startsOn:start,endsOn:end,visibility:"members",source:"manual",confirmedAt:new Date().toISOString(),...(link?{supportingUri:link}:{}),...(kind==="time_off"?{timeOffAvailability:"none" as const,...(label?{privateReason:label}:{})}:{hoursPerWeek:Number(d.get("hours")??0),color:COLORS[this.draftEntries.length%COLORS.length]??COLORS[0],...(label?{label}:{})})}];form.reset();};
  private change(index:number,key:string,value:unknown):void { this.draftEntries=this.draftEntries.map((entry,i)=>{if(i!==index)return entry;if(key!=="kind")return{...entry,[key]:value} as AvailabilityEntry;if(value==="time_off"){const{hoursPerWeek:_,label:__,color:___,...rest}=entry;return{...rest,kind:"time_off",timeOffAvailability:"none"};}const{timeOffAvailability:_,privateReason:__,...rest}=entry;return{...rest,kind:value as AvailabilityEntry["kind"],hoursPerWeek:entry.hoursPerWeek??0};}); }
  private readonly save=async():Promise<void>=>{const plan=this.workspace?.ownPlan;if(!plan)return;this.saving=true;this.error="";this.notice="";try{this.workspace=await this.client.replace({planId:plan.id,expectedVersion:plan.version,timeZone:this.draftTimeZone,defaultWeeklyHours:this.draftCapacity,entries:this.draftEntries});this.syncDraft();this.notice="Availability saved.";}catch(e){this.error=userError(e);}finally{this.saving=false;}};
  private async load():Promise<void>{this.loading=true;try{this.workspace=await this.client.get();this.selectedPersonId=this.workspace.viewerPersonId;this.syncDraft();}catch(e){this.error=userError(e);}finally{this.loading=false;}}
  private syncDraft():void{if(!this.workspace)return;this.draftEntries=this.workspace.ownPlan.entries.map(e=>({...e}));this.draftTimeZone=this.workspace.ownPlan.timeZone;this.draftCapacity=this.workspace.ownPlan.defaultWeeklyHours;}
  private shift(count:number):void{this.windowStart=add(this.windowStart,this.interval,count);}
  private get selectedPlan():AvailabilityPlan|undefined{return this.workspace?.visiblePlans.find(p=>p.personId===this.selectedPersonId);}
  private get selectedSummary():AvailabilitySummary|undefined{return this.workspace?.summaries.find(s=>s.personId===this.selectedPersonId);}
}
function kinds():readonly AvailabilityEntry["kind"][]{return["allocation","open_capacity","tentative","time_off"];}
function friendly(value:string):string{return value.split("_").map(x=>`${x[0]?.toUpperCase()??""}${x.slice(1)}`).join(" ");}
function today():string{return new Date().toISOString().slice(0,10);}
function date(iso:string):Date{return new Date(`${iso}T00:00:00Z`);}
function iso(value:Date):string{return value.toISOString().slice(0,10);}
function align(value:string,interval:Interval):string{const d=date(value);if(interval==="week")d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));if(interval==="month")d.setUTCDate(1);return iso(d);}
function add(value:string,interval:Interval,count:number):string{const d=date(value);if(interval==="month")d.setUTCMonth(d.getUTCMonth()+count);else d.setUTCDate(d.getUTCDate()+count*(interval==="week"?7:1));return iso(d);}
function bucket(start:string,interval:Interval,index:number){const from=add(start,interval,index);const until=add(from,interval,1);const end=iso(new Date(date(until).getTime()-DAY));return{start:from,end,label:interval==="month"?date(from).toLocaleDateString(undefined,{month:"short",year:"numeric",timeZone:"UTC"}):interval==="week"?`${from.slice(5)}–${end.slice(5)}`:date(from).toLocaleDateString(undefined,{month:"short",day:"numeric",timeZone:"UTC"})};}
function overlaps(entry:AvailabilityEntry,range:{start:string;end:string}):boolean{return entry.startsOn<=range.end&&entry.endsOn>=range.start;}
function userError(error:unknown):string{return error instanceof AvailabilityApiError?error.message:error instanceof Error?error.message:"Availability operation failed.";}
