import type { GovernedActionProjection, GovernanceWorkspaceProjection } from "@adminbot/api-contracts";
import { css, html, LitElement, nothing, type TemplateResult } from "lit";
import { GovernanceApiClient, type GovernanceClient } from "./governance-api-client.js";

export class AdminBotGovernanceActionsApp extends LitElement {
  static override properties={workspace:{state:true},busy:{state:true},error:{state:true}};
  static override styles=css`:host{display:block;color:var(--text)}*{box-sizing:border-box}h1{margin:0;color:var(--text-strong);font:500 clamp(2rem,5vw,3.5rem)/1.05 Georgia,serif}.lede{color:var(--text-muted);line-height:1.6}.banner,.error{padding:.7rem;border-left:.2rem solid var(--warning);background:var(--surface-2);font-size:.75rem}.error{color:var(--danger);border-color:var(--danger)}.queue{display:grid;gap:.8rem;margin-top:1rem}.action{border:1px solid var(--border);border-radius:.85rem;padding:1rem;background:var(--surface-2)}.top{display:flex;flex-wrap:wrap;justify-content:space-between;gap:.5rem}.badge{border-radius:99px;padding:.25rem .55rem;background:var(--accent-soft);color:var(--accent);font-size:.68rem}.meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:.5rem;margin:.8rem 0;font-size:.72rem;color:var(--text-muted)}code{overflow-wrap:anywhere;color:var(--text-strong)}details{margin:.7rem 0}pre{overflow:auto;max-height:18rem;padding:.7rem;background:var(--surface-1);font-size:.68rem}.buttons{display:flex;flex-wrap:wrap;gap:.5rem}button{border:1px solid var(--border-strong);border-radius:.55rem;padding:.5rem .7rem;color:var(--text);background:var(--surface-3);cursor:pointer}.approve{border-color:var(--accent);background:var(--accent);color:var(--accent-ink)}.reject{color:var(--danger)}button:disabled{opacity:.5}`;
  client:GovernanceClient=new GovernanceApiClient(import.meta.env.VITE_ADMINBOT_API_ORIGIN||window.location.origin);declare private workspace:GovernanceWorkspaceProjection|undefined;declare private busy:boolean;declare private error:string;
  constructor(){super();this.workspace=undefined;this.busy=false;this.error=""}override connectedCallback():void{super.connectedCallback();void this.load()}
  override render():TemplateResult{return html`<header><p>Governance · immutable actions</p><h1>Actions & approvals</h1><p class="lede">Review exact payloads, policy bindings, approval history, and verified execution state.</p></header>${this.workspace&&!this.workspace.reimbursementConnectorAvailable?html`<p class="banner">No reimbursement connector is configured. Approved actions fail closed at execution and no claim is reported as submitted.</p>`:nothing}${this.error?html`<p class="error" role="alert">${this.error}</p>`:nothing}<section class="queue">${this.workspace===undefined?html`<p>Loading actions…</p>`:this.workspace.actions.length===0?html`<p>No governed actions yet.</p>`:this.workspace.actions.map(action=>this.card(action))}</section>`}
  private card(action:GovernedActionProjection):TemplateResult{const canDecide=action.state==="awaiting_approval"&&action.requestedByPersonId!==this.workspace?.viewerPersonId;return html`<article class="action"><div class="top"><strong>${action.summary}</strong><span class="badge">${action.state.replaceAll("_"," ")} · ${action.risk}</span></div><div class="meta"><span>Requester<br><b>${action.requestedByName}</b></span><span>Policy<br><b>${action.policyVersion}</b></span><span>Approvals<br><b>${action.approvals.filter(item=>item.decision==="approve").length}/${action.approvalQuorum}</b></span><span>Expires<br><b>${new Date(action.expiresAt).toLocaleString()}</b></span></div><div>Payload hash<br><code>${action.payloadHash}</code></div><details><summary>Exact canonical payload</summary><pre>${JSON.stringify(action.canonicalPayload,null,2)}</pre></details>${action.approvals.map(item=>html`<p>${item.decision} · ${item.decidedByName} · ${new Date(item.decidedAt).toLocaleString()}</p>`)}${action.safeFailureCode?html`<p class="error">Execution stopped: ${action.safeFailureCode}</p>`:nothing}<div class="buttons">${canDecide?html`<button class="approve" ?disabled=${this.busy} @click=${()=>this.decide(action,"approve")}>Approve exact payload</button><button class="reject" ?disabled=${this.busy} @click=${()=>this.decide(action,"reject")}>Reject</button>`:nothing}${action.state==="approved"?html`<button ?disabled=${this.busy} @click=${()=>this.execute(action)}>Request execution</button>`:nothing}</div></article>`}
  private async load():Promise<void>{this.busy=true;try{this.workspace=await this.client.listActions();this.error=""}catch(error){this.error=message(error)}finally{this.busy=false}}
  private async decide(action:GovernedActionProjection,decision:"approve"|"reject"):Promise<void>{this.busy=true;try{await this.client.decide(action.id,{actionRevision:action.revision,payloadHash:action.payloadHash,policyDecisionId:action.policyDecisionId,decision});await this.load()}catch(error){this.error=message(error);this.busy=false}}
  private async execute(action:GovernedActionProjection):Promise<void>{this.busy=true;try{await this.client.execute(action.id,{actionRevision:action.revision,payloadHash:action.payloadHash,policyDecisionId:action.policyDecisionId})}catch(error){this.error=message(error)}finally{await this.load()}}
}
function message(error:unknown):string{return error instanceof Error?error.message:"Governance request failed."}
