import type { AdministratorPolicySettings, RoleName } from "@adminbot/api-contracts";
import { css, html, LitElement, nothing, type TemplateResult } from "lit";
import { GovernanceApiClient, type GovernanceClient } from "./governance-api-client.js";

export class AdminBotPolicySettingsApp extends LitElement {
  static override properties = { policy: { state: true }, busy: { state: true }, error: { state: true }, saved: { state: true } };
  static override styles = css`:host{display:block;color:var(--text)}*{box-sizing:border-box}h1{margin:0;color:var(--text-strong);font:500 clamp(2rem,5vw,3.5rem)/1.05 Georgia,serif}.lede{max-width:50rem;color:var(--text-muted);line-height:1.6}.panel{max-width:50rem;border:1px solid var(--border);border-radius:.85rem;padding:1rem;background:var(--surface-2)}form{display:grid;gap:.8rem}label{display:grid;gap:.3rem;color:var(--text-muted);font-size:.75rem}input[type=text],input[type=number],textarea{width:100%;border:1px solid var(--border-strong);border-radius:.55rem;padding:.6rem;color:var(--text-strong);background:var(--surface-1);font:inherit}.check{display:flex;gap:.5rem;align-items:center}.note,.error,.saved{padding:.7rem;border-left:.2rem solid var(--warning);background:var(--surface-1);font-size:.75rem}.error{color:var(--danger);border-color:var(--danger)}.saved{border-color:var(--accent)}button{justify-self:start;border:1px solid var(--accent);border-radius:.6rem;padding:.62rem .85rem;color:var(--accent-ink);background:var(--accent);font-weight:750;cursor:pointer}button:disabled{opacity:.5}`;
  client: GovernanceClient = new GovernanceApiClient(import.meta.env.VITE_ADMINBOT_API_ORIGIN || window.location.origin);
  declare private policy: AdministratorPolicySettings | undefined; declare private busy: boolean; declare private error: string; declare private saved: boolean;
  constructor(){super();this.policy=undefined;this.busy=false;this.error="";this.saved=false}
  override connectedCallback():void{super.connectedCallback();void this.load()}
  override render():TemplateResult{return html`<header><p>Administration · versioned policy</p><h1>Policy settings</h1><p class="lede">Manage reimbursement approval constraints and permitted destination identifiers. The T3 financial risk floor and approval requirement are fixed server-side.</p></header>${this.error?html`<p class="error" role="alert">${this.error}</p>`:nothing}${this.saved?html`<p class="saved" role="status">Policy version ${this.policy?.policyVersion} saved and audited.</p>`:nothing}${this.policy===undefined?html`<p>Loading policy…</p>`:this.form(this.policy)}`}
  private form(policy:AdministratorPolicySettings):TemplateResult{return html`<section class="panel"><p class="note">Current version ${policy.policyVersion} · record ${policy.version}. Changing policy invalidates execution of older approvals.</p><form @submit=${this.save}>
    <label class="check"><input name="enabled" type="checkbox" .checked=${policy.reimbursementSubmissionEnabled}> Accept new reimbursement proposals</label>
    <label>Eligible roles (comma-separated)<input name="roles" type="text" .value=${policy.reimbursementApprovalRoles.join(", ")} required></label>
    <label>Approval quorum<input name="quorum" type="number" min="1" max="5" .value=${String(policy.reimbursementApprovalQuorum)} required></label>
    <label class="check"><input name="requester" type="checkbox" .checked=${policy.reimbursementRequesterMayApprove}> Requester may approve their own proposal</label>
    <label class="check"><input name="distinct" type="checkbox" .checked=${policy.reimbursementDistinctApprovers}> Require distinct people</label>
    <label class="check"><input name="recent" type="checkbox" .checked=${policy.reimbursementRecentReauthenticationRequired}> Require recent reauthentication</label>
    <label>Approval expiry (hours)<input name="expiry" type="number" min="1" max="168" .value=${String(policy.reimbursementApprovalExpiryHours)} required></label>
    <label>Permitted destination identifiers (comma-separated)<input name="destinations" type="text" .value=${policy.reimbursementDestinations.join(", ")} required></label>
    <label>Reason for change<textarea name="reason" maxlength="2000" required></textarea></label>
    <button type="submit" ?disabled=${this.busy}>${this.busy?"Saving…":"Save reviewed policy"}</button></form></section>`}
  private async load():Promise<void>{this.busy=true;try{this.policy=await this.client.getPolicy();this.error=""}catch(error){this.error=message(error)}finally{this.busy=false}}
  private readonly save=async(event:SubmitEvent):Promise<void>=>{event.preventDefault();if(this.policy===undefined)return;this.busy=true;this.saved=false;const data=new FormData(event.currentTarget as HTMLFormElement);try{const roles=csv(data.get("roles")).filter((role):role is RoleName=>role==="administrator"||role==="approver");this.policy=await this.client.replacePolicy({expectedVersion:this.policy.version,reimbursementSubmissionEnabled:data.get("enabled")==="on",reimbursementApprovalRoles:roles,reimbursementApprovalQuorum:Number(data.get("quorum")),reimbursementRequesterMayApprove:data.get("requester")==="on",reimbursementDistinctApprovers:data.get("distinct")==="on",reimbursementRecentReauthenticationRequired:data.get("recent")==="on",reimbursementApprovalExpiryHours:Number(data.get("expiry")),reimbursementDestinations:csv(data.get("destinations")),reason:String(data.get("reason")??"").trim()});this.error="";this.saved=true}catch(error){this.error=message(error)}finally{this.busy=false}}
}
function csv(value:FormDataEntryValue|null):string[]{return [...new Set(String(value??"").split(",").map(item=>item.trim()).filter(Boolean))]}
function message(error:unknown):string{return error instanceof Error?error.message:"Policy request failed."}
