// Every paper on the `papers` tab of the contact sheet, placed on both maps.
//
// `areas` is the field taxonomy (see areas.ts); `sections` is the proposal's own agenda (see
// sections.ts). They are separate axes on purpose -- a funder reading the taxonomy wants to know
// what kind of safety work this lab does, and a reviewer reading the proposal wants to know which
// of its sections are already underway. The same paper answers both, differently.
//
// Deduplicated against the sheet, which lists a paper once per submission cycle it has been through:
// STRIDE, CLT-Forge, PruneGround, MoralGym, GT-HarmBench, the multilingual transcoder paper and the
// CoT graph-recovery paper each appear twice there. The canonical row here keeps the most complete
// author list and the furthest-along venue, and `alsoListedAs` records the other spelling so a
// reader checking the sheet against this table does not think a row went missing.
//
// The last group are not on the papers tab at all: they are the already-published results the
// proposal itself cites. A track record that omitted them would understate the lab by four
// peer-reviewed papers, so they are carried here with `published: true` and excluded from the
// pipeline counts.
//
// `sections: []` is a real answer, not missing data: lab output that no part of the technical
// agenda claims. The coverage panel counts those rows so the gap stays visible.

import type { SafetyAreaId } from "./areas.ts";

export type GrantPaper = {
  id: string;
  title: string;
  /** The venue column as the sheet records it, confidence estimate and all. */
  venue: string;
  /** The authors column, as recorded -- first names only where the sheet gives only first names. */
  authors: string;
  /** The sheet's own topic column, when the row carries one. */
  topic?: string;
  areas: readonly SafetyAreaId[];
  /** Ids from sections.ts. Empty when no part of the technical agenda claims this work. */
  sections: readonly string[];
  /** Set for prior results the proposal cites; these are not part of the current cycle. */
  published?: boolean;
  link?: string;
  alsoListedAs?: string;
};

export const GRANT_PAPERS: readonly GrantPaper[] = [
  // --- Evaluation validity and eval hacking -------------------------------------------------
  {
    id: "eval-hacking-ai4science",
    title: "Eval Hacking in AI4Science Benchmarks",
    venue: "100% ICLR",
    authors: "Shashwat, Terry",
    areas: ["evals"],
    sections: ["p1.1.1", "p1.1.1.C"],
  },
  {
    id: "eval-awareness",
    title: "Eval Awareness",
    venue: "NeurIPS 100%",
    authors: "Changling, Terry, Jie, Florian, Zhijing, Sahar, Maksym",
    topic: "Safety",
    areas: ["evals", "whiteBox"],
    sections: ["p1.1.1", "p1.1.1.B"],
    link: "https://arxiv.org/abs/2605.23055",
  },
  {
    id: "judging-the-judges",
    title: "Judging the Judges",
    venue: "NeurIPS 100%",
    authors: "Arth, Samuel, Bernhard, Zhijing",
    topic: "safety",
    areas: ["evals", "aiSolve"],
    sections: ["p1.1.1.C"],
  },
  {
    id: "mars-v",
    title: "MARS V Project",
    venue: "90% ICLR",
    authors: "Samuel, Arth, Lily, Nirav",
    topic: "Causality",
    areas: ["evals"],
    sections: ["p1.1.1"],
  },
  {
    id: "position-science-collaborative",
    title: "Position: Science is collaborative and LLM for Science should be too",
    venue: "NeurIPS 100% for feedback, then Nat/Sci",
    authors: "Terry",
    topic: "AI4Sci",
    areas: ["evals"],
    sections: ["p1.1.1"],
  },
  {
    id: "causality-monsters-benchmarks",
    title: "Causality can systematically address the monsters under the bench(marks)",
    venue: "",
    authors: "",
    areas: ["evals", "construction"],
    sections: ["p1.1.1.A"],
  },
  {
    id: "tda-sft",
    title: "Training Data Attribution for SFT",
    venue: "60% ICLR",
    authors: "Arth, Sekai and Stanford Collab (Nick Haber Lab)",
    areas: ["whiteBox", "evals"],
    sections: ["p1.1.1.A", "p1.1.4"],
  },
  {
    id: "if-rlvr",
    title: "Influence Functions Framework for RLVR",
    venue: "50% ICLR",
    authors: "Han, Terry",
    areas: ["whiteBox"],
    sections: ["p1.1.1.A", "p1.1.4"],
  },
  {
    id: "root-cause-mcp",
    title: "Root Cause Analysis for MCP Servers",
    venue: "Not decided",
    authors: "Calum, Rahul",
    topic: "Causality",
    areas: ["control"],
    sections: ["p1.1.1.C", "p1.3.1"],
  },

  // --- Misalignment -------------------------------------------------------------------------
  {
    id: "af-arena",
    title: "Alignment Faking: A systematic multi-dimensional testing suite (AF-Arena)",
    venue: "NeurIPS 100%",
    authors: "Chijoke, Terry, Zhijing",
    topic: "Safety",
    areas: ["evals", "whiteBox"],
    // Also under the EU AI Bench: that section's case rests on the benchmarks a clause can be
    // scored against being lab-built, and this is one of the four it names.
    sections: ["p1.1.2", "p1.1.5", "p1.2.4"],
    link: "https://openreview.net/forum?id=vFqn3kCuYV",
  },
  {
    id: "am-bench",
    title: "Eval Suite for Agentic Misalignment (incl. Scheming) (AM-Bench)",
    venue: "NeurIPS 100%",
    authors: "Eric, Terry, Chijoke, Zhijing",
    topic: "Safety",
    areas: ["evals", "whiteBox"],
    sections: ["p1.1.2", "p1.1.5", "p1.2.4"],
  },
  {
    id: "supersycophantic",
    title: "SuperSycophantic",
    venue: "NeurIPS 100% for feedback, then Nat/Sci",
    authors: "Terry, Oscar, Florent (many middle authors), Zhijing",
    topic: "Safety",
    areas: ["evals", "whiteBox"],
    sections: ["p1.1.2", "p1.1.5"],
  },
  {
    id: "gt-harmbench",
    title: "GT-HarmBench",
    venue: "NeurIPS 100%",
    authors: "From ICML",
    topic: "Safety",
    areas: ["evals"],
    sections: ["p1.1.2", "p1.3.1", "p1.2.4"],
  },
  {
    id: "long-context-gt-harmbench",
    title: "Long-context GT-HarmBench",
    venue: "100% ICLR",
    authors: "Sekai, Terry",
    areas: ["evals"],
    sections: ["p1.1.2", "p1.3.1"],
  },
  {
    id: "livehumanrightsbench",
    title: "LiveHumanRightsBench (LLM Sycophancy under Legal Debate)",
    venue: "100% ICLR",
    authors: "{Terry*, Arian*, Vladimir*} and many middle authors",
    areas: ["evals", "alignment"],
    sections: ["p1.1.2"],
  },
  {
    id: "second-order-bias",
    title: "Evaluating Second-Order Bias of LLMs Through Epistemic Entitlement",
    venue: "Findings of EMNLP 100%",
    authors:
      "Ramaravind Kommiya Mothilal, Terry Jingchen Zhang, Raiyan Ahmed, Zhijing Jin, Shion Guha, Syed Ishtiaque Ahmed",
    areas: ["evals"],
    sections: ["p1.1.2"],
  },
  {
    id: "multilingual-safety",
    title: "Multi-lingual safety stuff",
    venue: "",
    authors: "Chijoke, Terry",
    topic: "Multi-linguality",
    areas: ["evals"],
    sections: ["p1.1.2"],
  },
  {
    id: "vetha-merged-safety",
    title: "Revive Vetha's 2 papers into 1",
    venue: "EMNLP 100%",
    authors: "Sonny, Terry (Vetha in ack)",
    topic: "Safety",
    areas: ["evals"],
    sections: ["p1.1.2"],
  },
  {
    id: "misalignment-survey",
    title: "Survey of misalignment by level of goal-directedness",
    venue: "published",
    authors: "Lab survey",
    areas: ["evals", "alignment"],
    sections: ["p1.1.2"],
    published: true,
    link: "https://arxiv.org/abs/2604.04788",
  },

  // --- Adversarial defense ------------------------------------------------------------------
  {
    id: "weight-level-defenses",
    title: "Weight-Level Defenses Improve LLM Agent Adversarial Robustness",
    venue: "NeurIPS 100%",
    authors: "Memo, Samuel, Zhijing, Bernhard",
    topic: "Safety",
    areas: ["alignment", "construction"],
    sections: ["p1.1.3"],
  },
  {
    id: "reppo",
    title: "RepPO: Representation Preference Optimization",
    venue: "50% ICLR",
    authors: "Damiano, Samuel, Bernhard, Zhijing",
    topic: "Robustness",
    areas: ["alignment", "whiteBox"],
    sections: ["p1.1.3"],
  },
  {
    id: "predictive-representation-alignment",
    title: "Predictive Representation Alignment for Robust LLM Safety",
    venue: "EMNLP 70%",
    authors: "Samuel, Memo, Damiano, Zhijing, Bernhard",
    topic: "Robustness",
    areas: ["alignment", "whiteBox"],
    sections: ["p1.1.3"],
  },
  {
    id: "diffusion-concept-erasure",
    title: "Diffusion concept erasure defense with contrastive representation learning",
    venue: "90% ICLR",
    authors: "Samuel, Rishit, (others welcome)",
    topic: "Causality",
    areas: ["alignment", "construction"],
    sections: ["p1.1.3"],
  },
  {
    id: "adv-robustness-rlvr-triplet",
    title: "Adversarial Robustness with RLVR + Triplet loss",
    venue: "unsure",
    authors: "Suvajit, Samuel, Jacob",
    topic: "Safety+RL",
    areas: ["alignment"],
    sections: ["p1.1.3"],
  },
  {
    id: "moe-unlearning",
    title: "MoE LLM Unlearning",
    venue: "ICLR 77.77%",
    authors: "Khai",
    areas: ["alignment"],
    sections: ["p1.1.3"],
  },
  {
    id: "simko-emnlp2025",
    title: "Contrastive learning for harmful-use mitigation (Simko et al.)",
    venue: "EMNLP 2025",
    authors: "Simko et al.",
    areas: ["alignment", "construction"],
    sections: ["p1.1.3"],
    published: true,
    link: "https://aclanthology.org/2025.emnlp-main.1430/",
  },
  {
    id: "simko-icml2026-honeypot",
    title: "Honeypot training (Simko et al.)",
    venue: "ICML 2026",
    authors: "Simko et al.",
    areas: ["alignment", "control"],
    sections: ["p1.1.3"],
    published: true,
    link: "https://drive.google.com/file/d/1SS0R_ah7mOqSgZHkOViqAFA7YbLOVQLj/view?usp=sharing",
  },
  {
    id: "ozdincer-2026",
    title: "Weight-level defenses for agentic prompt injection (Ozdincer et al.)",
    venue: "2026",
    authors: "Ozdincer et al.",
    areas: ["alignment", "construction"],
    sections: ["p1.1.3"],
    published: true,
    link: "https://drive.google.com/file/d/1BC_r4ca7CPmFR6d2QzcXe0esuYp8paKH/view?usp=sharing",
  },
  {
    id: "hossain-2026",
    title: "Tamper-resistance stress benchmarking (Hossain et al.)",
    venue: "2026",
    authors: "Hossain et al.",
    areas: ["evals", "construction"],
    sections: ["p1.1.3"],
    published: true,
    link: "https://arxiv.org/pdf/2602.06911v2",
  },

  // --- Science of generalization ------------------------------------------------------------
  {
    id: "forget-facts",
    title: "How Do Language Models Forget Facts? Decomposing Suppression and Erosion",
    venue: "80% ICLR",
    authors: "Vedant, Florent, Bernhard, Zhijing",
    areas: ["whiteBox", "alignment"],
    sections: ["p1.1.4", "p1.1.5"],
    link: "https://www.overleaf.com/3597486326fncdydshtnbm",
  },
  {
    id: "learning-exceptions",
    title:
      "Learning Exceptions Without Overwriting the Rule: Coherence, Reuse, and Containment from Modular MLPs to Fine-Tuned LLMs",
    venue: "10% (in process)",
    authors: "Vincent, Vedant",
    topic: "Interp",
    areas: ["whiteBox", "alignment"],
    sections: ["p1.1.4", "p1.1.5"],
  },
  {
    id: "causal-foundational-models",
    title: "Causal Foundational Models",
    venue: "80% ICLR",
    authors: "Furkan, Luke, Dehan, Zhijing",
    topic: "Causality",
    areas: ["construction"],
    sections: ["p1.1.4"],
  },
  {
    id: "causal-discovery-llms",
    title: "Causal Discovery with LLMs",
    venue: "90% ICLR",
    authors: "Yahang, Erivan, Luke, Rahul, Dehan, Zhijing",
    areas: ["construction"],
    sections: ["p1.1.4"],
    link: "https://www.overleaf.com/project/69cd718b3080fb4fc875129d",
  },
  {
    id: "causal-finetuning",
    title: "Causal Finetuning",
    venue: "?",
    authors: "?",
    topic: "Robustness",
    areas: ["alignment", "construction"],
    sections: ["p1.1.4"],
  },
  {
    id: "training-dynamics-causal-reasoning",
    title: "Training Dynamics of Causal Reasoning in LLMs",
    venue: "ARR January or ICML",
    authors: "Rahul, Moritz (MPI-IS)",
    topic: "Causality",
    areas: ["whiteBox"],
    sections: ["p1.1.4"],
  },
  {
    id: "mechanistic-causal-reasoning",
    title: "A Mechanistic Study of Causal Reasoning in LLMs",
    venue: "Not decided",
    authors: "Rahul, Roderick, Udbhav",
    topic: "Causality",
    areas: ["whiteBox"],
    sections: ["p1.1.4", "p1.1.5"],
  },
  {
    id: "transfer-aware-curriculum-rl",
    title: "Transfer-Aware Curriculum Learning for RL",
    venue: "NeurIPS 100%",
    authors: "Yongjin, Zhijing",
    topic: "RL",
    areas: ["alignment"],
    sections: ["p1.1.4"],
  },
  {
    id: "cross-lingual-transfer-math",
    title: "Unsupervised Elicitation of Cross-Lingual Transfer in Math Reasoning",
    venue: "80% ARR Aug",
    authors: "Gopal, Rishitej, Terry",
    topic: "Multi-linguality / Post-Training",
    areas: ["aiSolve", "alignment"],
    sections: ["p1.1.4"],
    link: "https://www.overleaf.com/3374842454gttjvwqsthnn",
  },
  {
    id: "user-feedback-personas",
    title: "User-Feedback Contingency Shapes Assistant Personas",
    venue: "60% ICLR",
    authors: "Arth and Stanford Collab (Nick Haber Lab)",
    areas: ["alignment", "evals"],
    sections: ["p1.1.2", "p1.1.4"],
  },

  // --- Interpretability ---------------------------------------------------------------------
  {
    id: "linear-probes-emerge-cta",
    title:
      "How Do Linear Probes Emerge? A Circuit-Tracing Framework with Concept-Targeted Attribution",
    venue: "EMNLP 100%",
    authors: "Vedant Palit, Florent Draye, Terry Jingchen Zhang, Bernhard Schölkopf, Zhijing Jin",
    topic: "Interp",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
    link: "https://drive.google.com/file/d/1eqbCvj3q4GQ1Xw4KvRXepe3eB3A_mjzM/view?usp=sharing",
  },
  {
    id: "probes-circuits-equivalence",
    title:
      "Improving the Consistency of LLM Interpretability by Showing the Equivalence of Probes and Circuit Graphs",
    venue: "EMNLP 100%",
    authors: "Vedant, Florent, Zhijing, Bernhard",
    topic: "Interp",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
  },
  {
    id: "clt-forge",
    title: "CLT-Forge: A Scalable Library for Cross-Layer Transcoders and Attribution Graphs",
    venue: "EMNLP Demo 100%",
    authors:
      "Florent Draye, Abir Harrasse, Vedant Palit, Tung-Yu Wu, Jiarui Liu, Punya Syon Pandey, Terry Jingchen Zhang, Zhijing Jin, Bernhard Schölkopf",
    topic: "Interp",
    areas: ["whiteBox", "aiSolve"],
    sections: ["p1.1.5"],
    alsoListedAs: "CLT-Forge (EMNLP Demo), listed twice on the sheet",
  },
  {
    id: "tracing-multilingual-clt",
    title: "Tracing Multilingual Representations in LLMs with Cross-Layer Transcoders",
    venue: "EMNLP 100%",
    authors: "Abir Harrasse*, Florent Draye*, Punya Syon Pandey, Zhijing Jin†, Bernhard Schölkopf†",
    topic: "Interp / Multi-linguality",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
    alsoListedAs: "listed again as an EMNLP-or-commitment-only row",
  },
  {
    id: "graph-recovery-cot",
    title: "Computation Graph Recovery from Chain-of-Thought",
    venue: "EMNLP 100%",
    authors:
      "Roderick Wu, Florent Draye, Aydin Javadov, Bernhard Schölkopf, Terry Jingchen Zhang, Zhijing Jin",
    topic: "Interp",
    areas: ["whiteBox", "control"],
    sections: ["p1.1.5"],
    alsoListedAs: "Graph Recovery from CoT",
  },
  {
    id: "fluid-representations",
    title: "Fluid Representations in Reasoning Models",
    venue: "Findings of EMNLP 100%",
    authors:
      "Dmitrii Kharlapenko, Terry Jingchen Zhang, Arth Singh, Alessandro Stolfo, Arthur Conmy, Mrinmaya Sachan, Zhijing Jin",
    topic: "Interp",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
    alsoListedAs: "Fluid Reasoning Representation",
  },
  {
    id: "stride",
    title: "STRIDE",
    venue: "NeurIPS 50% / ICLR 50%",
    authors: "Rishit, Abir, Luke and others (Florent, Zhijing)",
    topic: "Interp",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
    alsoListedAs: "listed twice on the sheet, once per cycle",
  },
  {
    id: "riemannian-steering",
    title: "Riemannian Manifold Steering",
    venue: "60% ICLR",
    authors:
      "Narmeen Oozeer (Jinesis, Martian)*, Elisabetta Rochetti (Milan), Shivam Raval (Harvard), Manikandan Ravikaran",
    topic: "Interp",
    areas: ["whiteBox", "alignment"],
    sections: ["p1.1.5"],
  },
  {
    id: "detect-deception-probe",
    title: "Detect Deception by Interp (llama-70B probe)",
    venue: "ICLR?",
    authors: "Johannes, Terry, Florent",
    topic: "Interp",
    areas: ["whiteBox", "control"],
    sections: ["p1.1.5", "p1.1.1.B"],
  },
  {
    id: "cot-failure-mechanistic",
    title: "Understanding Failures in Reasoning LLMs through Mechanistic Analysis of CoT Traces",
    venue: "ICLR 70%",
    authors: "Atirath*, Jiarui*",
    topic: "Interp",
    areas: ["whiteBox", "control"],
    sections: ["p1.1.5"],
  },
  {
    id: "probing-prompt-biases",
    title: "Probing the Internal Structure of Prompt-Induced Biases in LLMs",
    venue: "EMNLP 100%",
    authors: "Prakhar",
    topic: "Interp",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
  },
  {
    id: "alignment-tuning-sycophancy-reps",
    title:
      "How Does Alignment Tuning Shape Representations of Sycophancy and Related Cue-Induced Biases in LLMs?",
    venue: "Findings of EMNLP 100%",
    authors: "Prakhar Gupta, Terry Jingchen Zhang, Florent Draye, Bernhard Schölkopf, Zhijing Jin",
    areas: ["whiteBox", "alignment"],
    sections: ["p1.1.5", "p1.1.2"],
  },
  {
    id: "multilingual-interp",
    title: "Multi-lingual interp stuff",
    venue: "",
    authors: "Faruna, Terry",
    topic: "Multi-linguality",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
  },
  {
    id: "if-multilingual-reasoning-qa",
    title: "IF Analysis on Multi-lingual Reasoning QA",
    venue: "later in summer",
    authors: "Leyla (FA), Terry",
    topic: "Interp",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
  },
  {
    id: "culture-within",
    title:
      "The Culture Within: Toward a Mechanistic Understanding of Cultural Reasoning in Large Language Models",
    venue: "X% X",
    authors: "Samee, Furkan, LG people, Zhijing, Rada",
    topic: "Causality",
    areas: ["whiteBox"],
    sections: ["p1.1.5"],
  },
  {
    id: "wedge-questions",
    title:
      "The Wedge Questions: Discovering Latent Cultural Boundaries in LLMs via Persona Projection Divergence",
    venue: "ICML Pluralistic Alignment Workshop",
    authors: "Yejin Son, Yongjin Yang, Ryan Faulkner, Seungwon Lim, Zhijing Jin",
    topic: "Pluralistic alignment, Interp",
    areas: ["whiteBox", "alignment"],
    sections: ["p1.1.5"],
  },

  // --- Power concentration and society ------------------------------------------------------
  {
    id: "rhetoric-power-concentration",
    title:
      "Measuring the Rhetoric of Power Concentration: Political Speech Tracks Institutional Weakness",
    venue: "90% ARR Aug",
    authors: "David G, Arka, Kem, Leyla",
    topic: "Speech Analysis",
    areas: ["evals"],
    sections: ["p1.2.1"],
  },
  {
    id: "political-speech-analysis",
    title: "Political Speech Analysis",
    venue: "EMNLP 0",
    authors: "Leyla, Zhijing",
    topic: "NLP for democracy",
    areas: ["evals"],
    sections: ["p1.2.1"],
  },
  {
    id: "simulating-democratic-deliberation",
    title:
      "Simulating Democratic Deliberation: Representing Pluralistic Preferences through Electoral Systems in Multi-Agent LLMs",
    venue: "Findings of EMNLP 100%",
    authors:
      "Ryan Faulkner, Stanisław Szufa, Daniel Hoyer, Terry Jingchen Zhang, Roland Bouffanais, Joel Z Leibo, Zhijing Jin",
    areas: ["evals", "construction"],
    sections: ["p1.2.1", "p1.3.1"],
  },
  {
    id: "llm-preferences-elections",
    title: "Evaluating LLM Preferences across Social Issues with Elections",
    venue: "EMNLP 100%",
    authors: "Ryan, Stanislaw, Dan, Terry, Roland, Joel, Zhijing",
    topic: "Multi-Agent / Alignment",
    areas: ["evals", "alignment"],
    sections: ["p1.2.1", "p1.3.1"],
  },
  {
    id: "historical-revisionism",
    title: "Preserving Historical Truth: Detecting Historical Revisionism in Large Language Models",
    venue: "EMNLP 100%",
    authors:
      "Francesco Ortu*, Joeun Yook*, Keenan Samway, Punya Syon Pandey, Bernhard Schölkopf, Alberto Cazzaniga, Rada Mihalcea, Zhijing Jin",
    areas: ["evals"],
    sections: ["p1.2.1"],
  },
  {
    id: "if-democratic-authoritarian",
    title: "IF Analysis on Democratic vs. Authoritarian",
    venue: "EMNLP 100%",
    authors: "Arth, Terry",
    topic: "Interp",
    areas: ["whiteBox"],
    sections: ["p1.2.1", "p1.1.5"],
    link: "https://www.overleaf.com/4614262427ytkwwftnwzbj",
  },
  {
    id: "coupbench",
    title: "CoupBench: Will LLMs help in coups/autocratization?",
    venue: "70% 31st September",
    authors: "Pepijn (looking for collabs)",
    areas: ["evals"],
    sections: ["p1.2.2"],
  },
  {
    id: "coupsim",
    title: "CoupSim: How to produce coup-proof automated institutions",
    venue: "",
    authors: "Pepijn",
    areas: ["construction", "control"],
    sections: ["p1.2.2"],
  },
  {
    id: "governance-scenario-exploration",
    title: "LLM Multi-Agent Framework for Governance Scenario Exploration",
    venue: "?",
    authors: "Erivan, Colomban, Chloé (Geneva)",
    topic: "Multi-Agent",
    areas: ["evals", "construction"],
    sections: ["p1.2.1", "p1.2.2"],
  },

  // --- Multi-agent --------------------------------------------------------------------------
  {
    id: "when-agents-lie",
    title: "When Agents Lie: Premeditation, Persistence, and Exploitation in Repeated Games",
    venue: "NeurIPS 100%",
    authors: "Jerick, Terry, Vincent Conitzer, Zhijing (senior coauthorship)",
    topic: "Safety",
    areas: ["evals"],
    sections: ["p1.1.2", "p1.3.1", "p1.3.2"],
    alsoListedAs: "When Agents Lie + Cheap Talk Merged (ICLR row)",
  },
  {
    id: "entropy-collapse-social-media",
    title: "Entropy Collapse in Agentic Social Media",
    venue: "EMNLP 2026 — rejected; revision in progress",
    authors: "Ayush Nangia, Aman Gokrani, Terry Jingchen Zhang, Zhijing Jin",
    topic: "Multi-Agent",
    areas: ["evals"],
    sections: ["p1.3.1"],
  },
  {
    id: "multi-agent-debate-tts",
    title: "Revisiting Multi-Agent Debate as Test-Time Scaling: When Does Multi-Agent Help?",
    venue: "",
    authors: "",
    areas: ["evals", "alignment"],
    sections: ["p1.3.1"],
  },
  {
    id: "wordplay",
    title: "WordPlay",
    venue: "EMNLP 50% May 25",
    authors: "Andrei, Bryan, Dev, Nicolas, Zhijing",
    topic: "Multi-Agent",
    areas: ["evals"],
    sections: ["p1.3.1"],
  },
  {
    id: "adminbot",
    title: "AdminBot",
    venue: "50% ARR October",
    authors: "Andrew, Joeun, Arian, Emilia, Arth, Zhijing",
    topic: "Multi-Agent",
    areas: ["control"],
    sections: ["p1.3.1"],
  },
  {
    id: "case-for-moral-agents",
    title:
      "The Case for Moral Agents: Prosocial agents dominate homo economicus under incomplete contracts",
    venue: "NeurIPS 100%",
    authors: "Angelo Huang, Charlie Tharas, Samuele Marro, Emanuele La Malfa, Zhijing",
    topic: "Multi-Agent",
    areas: ["construction", "alignment"],
    sections: ["p1.3.2"],
    alsoListedAs: "Incomplete Contracts paper (ICLR row)",
  },
  {
    id: "position-institutional-design",
    title:
      "Position: Multi-Agent AI Systems Need Institutional Design, Not Just Model-Level Alignment",
    venue: "NeurIPS 70%",
    authors: "Van, Angelo, Erivan, Ryan, Joel Christoph (external), Terry, David, Zhijing",
    topic: "Multi-Agent",
    areas: ["construction", "control"],
    sections: ["p1.3.2"],
  },
  {
    id: "sanctioning-variants",
    title:
      "Sanctioning variants: mechanism design and incentive structure determine collective outcomes",
    venue: "EMNLP 0% (continuing for the next ARR or ICLR/NeurIPS)",
    authors: "Van, Angelo, Erivan, Ryan, Terry, David, Zhijing + maybe others",
    topic: "Multi-Agent",
    areas: ["construction", "control"],
    sections: ["p1.3.2"],
  },
  {
    id: "elected-leadership",
    title: "Evaluating Cooperation in LLM Social Groups through Elected Leadership",
    venue: "100% ARR",
    authors: "Ryan, David, Zhijing",
    topic: "Multi-Agent",
    areas: ["evals", "construction"],
    sections: ["p1.3.1", "p1.3.2"],
  },
  {
    id: "when-ethics-payoffs-diverge",
    title: "When Ethics and Payoffs Diverge: LLM Agents in Morally Charged Social Dilemmas",
    venue: "EMNLP 100%",
    authors: "Steffen, David, Terry",
    topic: "Multi-Agent",
    areas: ["evals", "alignment"],
    sections: ["p1.3.2"],
  },
  {
    id: "transparency-osgt",
    title: "Transparency in Open Source Game Theory",
    venue: "JMLR end of September",
    authors: "Colomban, Pepijn, Riccardo",
    topic: "Game Theory",
    areas: ["construction"],
    sections: ["p1.3.2"],
  },
  {
    id: "llms-osgt",
    title: "LLMs in Open Source Game Theory",
    venue: "80% ICML",
    authors: "Colomban, Pepijn, Riccardo",
    topic: "Game Theory",
    areas: ["evals", "construction"],
    sections: ["p1.3.2"],
  },
  {
    id: "moralgym",
    title: "MoralGym: Finetuning Cooperative LLM Agents",
    venue: "90% ICLR (ZJ: ARR suggested, given the ICLR submission limit) / EMNLP 10%",
    authors: "Yves, Joeun, Zhijing",
    topic: "Post-Training",
    areas: ["alignment"],
    sections: ["p1.3.2", "p1.1.2"],
    alsoListedAs: "listed twice on the sheet, once per cycle",
  },
  {
    id: "rl-game-theory",
    title: "RL for game theory",
    venue: "EMNLP 80%",
    authors: "Colomban, Arth, Pepijn, Zhijing",
    topic: "Post-Training",
    areas: ["alignment"],
    sections: ["p1.3.2"],
  },
  {
    id: "evolutionary-cooperation",
    title: "Evolutionary pressures for cooperative language models",
    venue: "80% ICLR (ZJ: ARR suggested, given the ICLR submission limit)",
    authors: "Mariana",
    topic: "Post-Training",
    areas: ["alignment"],
    sections: ["p1.3.2"],
  },
  {
    id: "evolution-of-cooperation",
    title: "The Evolution of Cooperation in Artificial Systems",
    venue: "NeurIPS 10%",
    authors: "Mariana, David, Terry, Zhijing",
    topic: "Multi-Agent",
    areas: ["alignment", "construction"],
    sections: ["p1.3.2"],
  },

  // --- Causal AI-for-science ----------------------------------------------------------------
  {
    id: "causal-ai-scientist",
    title: "Causal AI Scientist: Towards End-to-End Causal Inference with LLMs",
    venue: "ARR October",
    authors: "Rahul, Aryan, Erivan, ...",
    topic: "Causality",
    areas: ["construction", "aiSolve"],
    sections: ["p1.1.4"],
  },
  {
    id: "causal-ai-scientist-whitepaper",
    title: "Causal AI Scientist whitepaper (to Nature)",
    venue: "later in summer",
    authors: "",
    areas: ["construction", "aiSolve"],
    sections: ["p1.1.4"],
  },
  {
    id: "causal-tutor",
    title: "Causal Tutor",
    venue: "EMNLP 100%",
    authors: "Zaryab, Rahul, Aryan, Omar, Terry, Xianlin, Bernhard, Zhijing",
    topic: "Causality",
    areas: ["construction"],
    sections: [],
  },
  {
    id: "causal-data-agent",
    title: "Causal Data Agent",
    venue: "EMNLP 100%",
    authors: "Max*, Udbhav*, Andrew*, Rahul, Terry, Bernhard, Zhijing",
    topic: "Causality",
    areas: ["construction", "aiSolve"],
    sections: ["p1.1.4"],
  },

  // --- Lab output the technical agenda does not claim ---------------------------------------
  {
    id: "raptor",
    title: "RAPTOR: Role-Aware Private Training for Mixture-of-Experts",
    venue: "AAAI 100%",
    authors: "Khai",
    areas: ["construction"],
    sections: [],
  },
  {
    id: "vlm-3d-reasoning",
    title: "Where Do Vision Language Models Fail at 3D Reasoning?",
    venue: "96% (NAACL or Nature?)",
    authors: "Khai",
    areas: ["evals"],
    sections: [],
  },
  {
    id: "deep-case-report",
    title: "Deep Case Report",
    venue: "55.55%",
    authors: "Khai",
    areas: ["evals"],
    sections: [],
  },
  {
    id: "s-think",
    title: "S-Think: Segmentation-grounded thinking with medical images",
    venue: "ICLR 33.33%",
    authors: "Khai & 100 authors",
    areas: [],
    sections: [],
  },
  {
    id: "blind-agent",
    title: "Blind agent",
    venue: "22.22%",
    authors: "Khai & 150 authors",
    areas: [],
    sections: [],
  },
  {
    id: "length-penalized-rl",
    title: "Length-penalized RL for Math Reasoning",
    venue: "55.55%",
    authors: "Khai",
    areas: [],
    sections: [],
  },
  {
    id: "prune-ground",
    title: "PruneGround: Language-Guided Spatial Pruning for Efficient 3D Visual Grounding",
    venue: "EMNLP 100%",
    authors:
      "Duc Cao Dinh, Khai Le-Duc, Florent Draye, Chris Ngo, Terry Jingchen Zhang, Bernhard Schölkopf, Zhijing Jin",
    topic: "Multimodality",
    areas: [],
    sections: [],
    alsoListedAs: "listed twice on the sheet, once per cycle",
  },
  {
    id: "mixsd",
    title: "MixSD: Mixed Contextual Self-Distillation for Knowledge Injection",
    venue: "NeurIPS 100%",
    authors: "Jiarui, Lechen, Yongjin, Yinghui, Yingheng Wang, Weihao Xuan, Zhijing, Mona",
    topic: "Distillation",
    areas: [],
    sections: [],
  },
  {
    id: "hybrid-distillation",
    title:
      "Making Complex Reasoning Student-Friendly: A Hybrid Distillation Framework for Small Language Models",
    venue: "",
    authors: "",
    areas: [],
    sections: [],
  },
  {
    id: "memory-mechanisms",
    title: "What Is Memory, How Ought We Store It, and When Will My Memory Mechanism Perform Well?",
    venue: "NeurIPS 90%",
    authors: "Andrei, Atirath, Shuquan (Logan), Zhijing Jin, Nicolas Papernot",
    topic: "Memory",
    areas: [],
    sections: [],
  },
];

export const GRANT_PAPER_BY_ID: Readonly<Record<string, GrantPaper>> = Object.fromEntries(
  GRANT_PAPERS.map((paper) => [paper.id, paper]),
);
