// Generated from extensions/adminbot/deadlines/venues.json by
// scripts/adminbot-deadline-collect.py. Do not hand-edit; regenerate instead.

export type DeadlineVenue = {
  id: string;
  name: string;
  venue_type: string;
  venue_group: string;
  track?: string;
  deadline_label: string;
  deadline_aoe: string;
  notification_aoe?: string;
  link?: string;
};

export const DEADLINE_VENUES: DeadlineVenue[] = [
  {
    "id": "emnlp2026_commitment",
    "name": "EMNLP 2026 (main, ARR commitment)",
    "venue_type": "conference",
    "venue_group": "EMNLP 2026",
    "track": "main",
    "deadline_label": "commitment",
    "deadline_aoe": "2026-08-02 23:59:59",
    "notification_aoe": "2026-08-20 23:59:59",
    "link": "https://2026.emnlp.org/"
  },
  {
    "id": "arr_2026_august",
    "name": "ARR — August 2026 cycle (submission)",
    "venue_type": "conference",
    "venue_group": "ARR August 2026",
    "track": "main",
    "deadline_label": "ARR submission",
    "deadline_aoe": "2026-08-03 23:59:59",
    "notification_aoe": "",
    "link": "https://aclrollingreview.org/dates"
  },
  {
    "id": "emnlp2026_ws_nlp4pi",
    "name": "NLP4PI — 5th Workshop on NLP for Positive Impact (EMNLP 2026)",
    "venue_type": "workshop",
    "venue_group": "EMNLP 2026 Workshops",
    "track": "workshop",
    "deadline_label": "ARR commitment",
    "deadline_aoe": "2026-08-03 23:59:59",
    "notification_aoe": "2026-08-15 23:59:59",
    "link": "https://openreview.net/group?id=EMNLP/2026/Workshop/NLP4PI_ARR_Commitment"
  },
  {
    "id": "neurips2026_rebuttal",
    "name": "NeurIPS 2026 — Author rebuttal / discussion",
    "venue_type": "rebuttal",
    "venue_group": "NeurIPS 2026",
    "track": "rebuttal",
    "deadline_label": "rebuttal ends",
    "deadline_aoe": "2026-08-03 23:59:59",
    "notification_aoe": "",
    "link": "https://neurips.cc/Conferences/2026"
  },
  {
    "id": "neurips2026_ws_HAIC",
    "name": "2026 NeurIPS Workshop Human-AI Coevolution",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "http://Neurips2026haic.com"
  },
  {
    "id": "neurips2026_ws_AABA4ET",
    "name": "2nd Workshop on Agentic AI Benchmarks and Applications for Enterprise Tasks (NeurIPS 2026)",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://sites.google.com/view/aaba4et"
  },
  {
    "id": "neurips2026_ws_AutoMLR",
    "name": "40th Conference on Neural Information Processing Systems Workshop for Autonomous Machine Learning Research",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://automlr.com"
  },
  {
    "id": "neurips2026_ws_WRL",
    "name": "8th Robot Learning Workshop:  Is Physical AI Going Zero-Shot?",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://www.robot-learning.ml/2026/"
  },
  {
    "id": "neurips2026_ws_AI4PowerGrids",
    "name": "AI Foundations for Power Grids @ NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://ai4powergrids.github.io"
  },
  {
    "id": "neurips2026_ws_AI_and_the_Self",
    "name": "AI and the Self: Human Identity, Authenticity, and Agency in the Age of AI",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://aintheself.github.io/"
  },
  {
    "id": "neurips2026_ws_ASCI",
    "name": "AI at Scale for Clinical Impact: Cancer Pathology Foundation Models",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://asci.artificialintelligencepathology.org/"
  },
  {
    "id": "neurips2026_ws_AI4Mat",
    "name": "AI for Accelerated Materials Design - NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://sites.google.com/view/ai4mat/home"
  },
  {
    "id": "neurips2026_ws_AI4ChipDesign",
    "name": "AI for Chip Design - NeurIPS 2026 Workshop",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://neurips-ai-for-chip-design-2026.github.io/"
  },
  {
    "id": "neurips2026_ws_AIDaR",
    "name": "AIDaR: AI Data Readiness for Scientific Discovery",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://aidar-workshop.github.io/2026/"
  },
  {
    "id": "neurips2026_ws_AXIOM",
    "name": "AXIOM: Foundations of Efficient Deep Learning",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://axiom-neurips2026.github.io/"
  },
  {
    "id": "neurips2026_ws_Africa_in_AI",
    "name": "Africa in AI Affinity Group at Neural Information Processing Systems (NeurIPS) 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://africainai.mailab.io/"
  },
  {
    "id": "neurips2026_ws_BeNTo",
    "name": "Beyond Next Token Prediction: Diffusion and Flow Models for Next-Generation Decoding",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://bento-neurips.github.io/"
  },
  {
    "id": "neurips2026_ws_InfPriv",
    "name": "Beyond Private Training: The New Landscape of AI Privacy",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://beyond-private-training.ai.studio/"
  },
  {
    "id": "neurips2026_ws_DevAI",
    "name": "DevAI Workshop: Developmental Perspectives on AI",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://sites.google.com/view/devai-workshop-2026/"
  },
  {
    "id": "neurips2026_ws_DiffuLM",
    "name": "Diffusion Language Models: Foundations, Efficiency, and Reasoning",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://7amin.github.io/diffulm-neurips2026/"
  },
  {
    "id": "neurips2026_ws_DynaFront",
    "name": "Dynamics at the Frontiers of Optimization, Sampling, and Games",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://sites.google.com/view/dynafrontneurips26"
  },
  {
    "id": "neurips2026_ws_Meta-Agents",
    "name": "First Workshop on Meta Agents: Managing Agents that Manage Agents",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://meta-agents-workshop.github.io/"
  },
  {
    "id": "neurips2026_ws_JUDGe",
    "name": "First Workshop on Reliable Evaluation for Language Models (JUDGe)",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://judge2026.github.io"
  },
  {
    "id": "neurips2026_ws_FAST",
    "name": "Foundations of Agentic Systems Theory",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://fast-workshop.github.io"
  },
  {
    "id": "neurips2026_ws_FLMSec",
    "name": "Foundations of Language Model Security: Theory, Practice, and Fundamental Limits",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://flmsec.github.io/"
  },
  {
    "id": "neurips2026_ws_VLM4RWD",
    "name": "Grounded and Faithful Vision-Language Models for Real-World Deployment 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://vlm4rwd.github.io"
  },
  {
    "id": "neurips2026_ws_ICBINB-BIO",
    "name": "I Can’t Believe It’s Not Better (ICBINB): Failure Modes of AI in Biology",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://icbinb-bio.github.io/"
  },
  {
    "id": "neurips2026_ws_InterpScience",
    "name": "Interpretability as a Science: NeurIPS 2026 Workshop",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://interpscience.github.io/"
  },
  {
    "id": "neurips2026_ws_LXAI",
    "name": "LatinX in AI Workshop @ NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://www.latinxinai.org/neurips-2026"
  },
  {
    "id": "neurips2026_ws_MLForSys",
    "name": "Machine Learning for Systems 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://mlforsystems.org"
  },
  {
    "id": "neurips2026_ws_AI4Science",
    "name": "NeurIPS 2026 AI for Science Workshop: Verification in the Age of AI Scientists",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://ai4sciencecommunity.github.io/neurips26.html"
  },
  {
    "id": "neurips2026_ws_AgenticLS",
    "name": "NeurIPS 2026 Agentic AI for Biological Discovery Workshop",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://agenticls.github.io"
  },
  {
    "id": "neurips2026_ws_GlobalSouthAI",
    "name": "NeurIPS 2026 GlobalSouthAI",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://sites.google.com/view/globalsouthai-neurips26/home"
  },
  {
    "id": "neurips2026_ws_MLxOR",
    "name": "NeurIPS 2026 Second Workshop on ML×OR: Mathematical Foundations and Operational Integration of Machine Learning for Uncertainty-Aware Decision-Making",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://mlxor-2026.github.io/"
  },
  {
    "id": "neurips2026_ws_TAE",
    "name": "NeurIPS 2026 Trust-AI-Eval Workshop",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://tai-eval.github.io"
  },
  {
    "id": "neurips2026_ws_EvoRobust",
    "name": "NeurIPS 2026 Workshop - Self-Evolving Diversity-Driven Search for Robust AI Systems",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://neurips.cc/Conferences/2026"
  },
  {
    "id": "neurips2026_ws_RTCA",
    "name": "NeurIPS 2026 Workshop Real-Time Conversational Agents: Toward Natural Multimodal Interaction",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://rtcaneurips26.github.io/"
  },
  {
    "id": "neurips2026_ws_Verify-Agents",
    "name": "NeurIPS 2026 Workshop Who Verifies the Agents? Toward Reliable Agent Development",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://verify-agents-workshop.github.io/"
  },
  {
    "id": "neurips2026_ws_AI4DD",
    "name": "NeurIPS 2026 Workshop on AI for Drug Discovery: Bridging the Translation Gap",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://ai4dd-neurips2026.github.io/"
  },
  {
    "id": "neurips2026_ws_AI4MetaScience",
    "name": "NeurIPS 2026 Workshop on AI for Meta‑Science: Scaling and Organizing Science in the Age of AI",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://ai4metascience.org/"
  },
  {
    "id": "neurips2026_ws_STODY",
    "name": "NeurIPS 2026 Workshop on AI for Stochastic Dynamics: From Theoretical Foundations to Scientific Applications",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://eethanshi.github.io/stochastic-dynamics-2026/"
  },
  {
    "id": "neurips2026_ws_VERICODEGEN",
    "name": "NeurIPS 2026 Workshop on AI for Verifiable Coding",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://vericodegen.github.io/"
  },
  {
    "id": "neurips2026_ws_AI-Native_Academia",
    "name": "NeurIPS 2026 Workshop on AI-Native Academia: Authorship, Peer Review, and Conference Governance under AI",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://ai-native-academia.github.io"
  },
  {
    "id": "neurips2026_ws_ML4Molecules",
    "name": "NeurIPS 2026 Workshop on Agentic Systems for Molecular Sciences",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://moleculediscovery.github.io/workshop2026/"
  },
  {
    "id": "neurips2026_ws_Child_Safety_in_AI",
    "name": "NeurIPS 2026 Workshop on Child Safety in AI",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://childsafety-ai.github.io/"
  },
  {
    "id": "neurips2026_ws_CLEA",
    "name": "NeurIPS 2026 Workshop on Continual Learning for Enterprise AI Agents",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://clea-neurips.github.io/"
  },
  {
    "id": "neurips2026_ws_CL4FMAgents",
    "name": "NeurIPS 2026 Workshop on Continual Learning in the Era of Foundation Models and Embodied Agents",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://neurips26-cl4fmagents.github.io"
  },
  {
    "id": "neurips2026_ws_CWM",
    "name": "NeurIPS 2026 Workshop on Continual World Models",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://continual-world-models-workshop.github.io"
  },
  {
    "id": "neurips2026_ws_BiAlign",
    "name": "NeurIPS 2026 Workshop on Dynamic Alignment in Human-AI Coupled Systems",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://bialign-workshop.github.io/"
  },
  {
    "id": "neurips2026_ws_E-values",
    "name": "NeurIPS 2026 Workshop on E-values: From Statistics To ML",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://e-values-workshop.github.io/"
  },
  {
    "id": "neurips2026_ws_FLLMPT",
    "name": "NeurIPS 2026 Workshop on Foundations of LLM Post-Training in Changing Environments",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://www.fllmpt-work.shop/"
  },
  {
    "id": "neurips2026_ws_Interp4Discovery",
    "name": "NeurIPS 2026 Workshop on Interpretability for Discovery",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://interpretability4discovery.github.io/"
  },
  {
    "id": "neurips2026_ws_LP4FM",
    "name": "NeurIPS 2026 Workshop on Linguistic Principles for Foundation Models",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://lp4fm.github.io/"
  },
  {
    "id": "neurips2026_ws_PhysUnderstand",
    "name": "NeurIPS 2026 Workshop on Physical Understanding for Decision-Making: Bridging Foundation Models and Reliable Agents",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "sites.google.com/view/neurips-2026-workshop-pudm"
  },
  {
    "id": "neurips2026_ws_PriGM",
    "name": "NeurIPS 2026 Workshop on Principles of Generative Modeling (PriGM)",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://sites.google.com/view/prigmneurips2026/home"
  },
  {
    "id": "neurips2026_ws_ReMuCAI",
    "name": "NeurIPS 2026 Workshop on Real-Time Multimodal Conversational AI",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://sites.google.com/view/remucai"
  },
  {
    "id": "neurips2026_ws_SaTQuML",
    "name": "NeurIPS 2026 Workshop on SaTQuML: Secure and Trustworthy Quantum Machine Learning",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://satquml.github.io/"
  },
  {
    "id": "neurips2026_ws_NeurReps_Extended_Abstracts",
    "name": "NeurIPS 2026 Workshop on Symmetry and Geometry in Neural Representations (Extended Abstract Track)",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://neurreps.org/"
  },
  {
    "id": "neurips2026_ws_NeurReps_Findings",
    "name": "NeurIPS 2026 Workshop on Symmetry and Geometry in Neural Representations (Findings Track)",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://neurreps.org/"
  },
  {
    "id": "neurips2026_ws_NeurReps_Proceedings",
    "name": "NeurIPS 2026 Workshop on Symmetry and Geometry in Neural Representations (Proceedings Track)",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://neurreps.org/"
  },
  {
    "id": "neurips2026_ws_TTCL",
    "name": "NeurIPS 2026 Workshop on Towards Test-Time Continual Learning Agents",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "ttcl-agents.github.io"
  },
  {
    "id": "neurips2026_ws_GDDL",
    "name": "NeurIPS 2026 Workshop: Bridging Optimal Transport, Learning and Structured Data: Toward Geometric Distributional Learning",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://gddl-neurips-2026.github.io"
  },
  {
    "id": "neurips2026_ws_EIML",
    "name": "NeurIPS 2026 Workshop: Epistemic Intelligence in Machine Learning",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://epistemic-intelligence-in-ml.github.io"
  },
  {
    "id": "neurips2026_ws_PALM",
    "name": "NeurIPS 2026 Workshop: Personalized, Aligned, Long-Term Memory for AI Systems",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://palm-neurips-2026.github.io/"
  },
  {
    "id": "neurips2026_ws_Pre-to-Post",
    "name": "NeurIPS 2026 Workshop: Transitioning from Pre-Training to Post-Training",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://pretrain2posttrain.github.io"
  },
  {
    "id": "neurips2026_ws_CODEC-FM",
    "name": "NeurIPS Workshop on Collaborative, Open, and Decentralized Training of Foundation Models",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://collaborative-open-decentralized-fomo.github.io/"
  },
  {
    "id": "neurips2026_ws_ML4SpatialBio",
    "name": "NeurIPS Workshop on Machine Learning for Spatially Resolved High-dimensional Biology",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://imsb-uke.github.io/ml4spatialbio-2026/"
  },
  {
    "id": "neurips2026_ws_LIGHT",
    "name": "Neurips 2026 Workshop - LIGHT: Deployable Small Foundation Models",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://almaai-disi-unibo.github.io/neurips2026-light-smallModels/"
  },
  {
    "id": "neurips2026_ws_NEmo",
    "name": "Neuro-Symbolic Embodied Intelligence",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://nemo.semantic.review/"
  },
  {
    "id": "neurips2026_ws_NewInML",
    "name": "New In Machine Learning (NewInML) Workshop @NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://newinml.github.io/NewInML2026NeurIPS/"
  },
  {
    "id": "neurips2026_ws_OPT",
    "name": "OPT 2026: Optimization for Machine Learning (NeurIPS 2026 Workshop)",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://opt-ml.org/"
  },
  {
    "id": "neurips2026_ws_ODI",
    "name": "On-Device Intelligence: Foundation Models under Real-World Constraints",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://odi2026.github.io/"
  },
  {
    "id": "neurips2026_ws_PTA",
    "name": "PTA: From Pretrained Representations to Acting Agents",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://ptaworkshop.github.io/"
  },
  {
    "id": "neurips2026_ws_MPLR-FM",
    "name": "Privacy in the Era of Large Opaque Models: Theoretical, Legal, and Practical Perspectives",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://neurips-workshop2026.github.io/foundation_model_agentic_privacy/"
  },
  {
    "id": "neurips2026_ws_QueerInAI",
    "name": "Queer in AI and {Dis}Ability in AI Workshop at NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://www.queerinai.com/neurips-2026"
  },
  {
    "id": "neurips2026_ws_RL4XS",
    "name": "Reinforcement Learning for Experimental Sciences Workshop",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://rl-experimental-sciences-workshop.github.io/"
  },
  {
    "id": "neurips2026_ws_RPS",
    "name": "Representations for the Physical Sciences Workshop @ NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://representations-physical-sciences.github.io/workshop-2026/"
  },
  {
    "id": "neurips2026_ws_RCMLR",
    "name": "Responsible Communication of Machine Learning Research in Biomedicine",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://translatingmlresearch.github.io/RCMLR/"
  },
  {
    "id": "neurips2026_ws_RoCo-Spring",
    "name": "RoCo-Spring: The Robust Correspondence Challenge",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://roco-spring.github.io/"
  },
  {
    "id": "neurips2026_ws_RoboPAD",
    "name": "RoboPAD: Post-Training Adaptation of Robot Foundation Models",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://robotpad2026.github.io/"
  },
  {
    "id": "neurips2026_ws_Robotics_World_Modeling",
    "name": "Robot Learning with World Models: Capabilities, Frontiers, and Challenges",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://robowm-ws.github.io/"
  },
  {
    "id": "neurips2026_ws_SLM-Agents",
    "name": "SLM-Agents: 1st NeurIPS Workshop on SLMs for Agentic Systems",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://slmw2026.github.io/"
  },
  {
    "id": "neurips2026_ws_SocialAgent",
    "name": "Second Workshop on Large Language Models for Social Reasoning and Simulation",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://social-llm-workshop.github.io/"
  },
  {
    "id": "neurips2026_ws_Sim2Sci",
    "name": "Sim2Science: ML with Imperfect Scientific Models",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://www.sim2science.com/"
  },
  {
    "id": "neurips2026_ws_TCCML",
    "name": "Tackling Climate Change with Machine Learning: workshop at NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://www.climatechange.ai/events/neurips2026"
  },
  {
    "id": "neurips2026_ws_IAB",
    "name": "The 1st Workshop on Interpreting Agent Behavior (IAB) at NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://iab-agents.github.io/"
  },
  {
    "id": "neurips2026_ws_IAB_Competition_Paper_Track",
    "name": "The 1st Workshop on Interpreting Agent Behavior (IAB) at NeurIPS 2026 - Competition Paper Track",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "http://glee-competition.com; https://iab-agents.github.io/"
  },
  {
    "id": "neurips2026_ws_PhysWorldAI",
    "name": "The 1st Workshop on Physical World AI: Geometry, Characteristics, and Multimodal Sensing (NeurIPS 2026)",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://physworld-org.github.io/physworld.github.io/"
  },
  {
    "id": "neurips2026_ws_Simbiochem",
    "name": "The 2nd Workshop on Simulations for Biology and Chemistry",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "www.simbiochem.com"
  },
  {
    "id": "neurips2026_ws_MusIML",
    "name": "The 7th Muslims in ML (MusIML) Workshop at NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://www.musiml.org/"
  },
  {
    "id": "neurips2026_ws_MATH-AI",
    "name": "The Sixth Workshop on Mathematical Reasoning and AI",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://mathai-2026.github.io/"
  },
  {
    "id": "neurips2026_ws_GenAI4Health",
    "name": "The Third Workshop on GenAI for Health: Agentic Systems, Clinical Trust, and Future Potential",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://genai4health.github.io/"
  },
  {
    "id": "neurips2026_ws_GenAI4Health_Demonstration_Paper_Track",
    "name": "The Third Workshop on GenAI for Health: Agentic Systems, Clinical Trust, and Future Potential - Demonstration Paper Track",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://genai4health.github.io/"
  },
  {
    "id": "neurips2026_ws_GenAI4Health_Position_Paper_Track",
    "name": "The Third Workshop on GenAI for Health: Agentic Systems, Clinical Trust, and Future Potential - Position Paper Track",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://genai4health.github.io/"
  },
  {
    "id": "neurips2026_ws_ATTRIB",
    "name": "Third NeurIPS Workshop on Attributing Model Behavior at Scale: Data Attribution and Provenance",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://attrib-workshop.cc/"
  },
  {
    "id": "neurips2026_ws_AIWILD",
    "name": "Third Workshop on Agents in the Wild: Safety, Security, and Beyond",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://agentwild-workshop.github.io/neurips2026/"
  },
  {
    "id": "neurips2026_ws_AI4GOOD",
    "name": "Trustworthy AI for Good (AI4GOOD) Workshop @ NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://trustworthy-ai-for-good.github.io/"
  },
  {
    "id": "neurips2026_ws_WiML",
    "name": "Women in Machine Learning Workshop @ NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://www.wiml.org/"
  },
  {
    "id": "neurips2026_ws_TS-LIMITS",
    "name": "Workshop TS-LIMITS @NeurIPS 2026 -- Generalization for Time Series in Tight Settings: Latency, Inference, Memory, prIvacy and susTainability",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://ts-limits.github.io/"
  },
  {
    "id": "neurips2026_ws_EconML",
    "name": "Workshop on Economics for Machine Learning at NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://safwanhossain.github.io/"
  },
  {
    "id": "neurips2026_ws_IAEval",
    "name": "Workshop on Evaluation of Interactive Agents @ NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://eval-interactive-agents-workshop.github.io/"
  },
  {
    "id": "neurips2026_ws_WMHS",
    "name": "World Models for High-Stakes Health: Reliable Clinical Trial Simulation and Intervention-Aware Reasoning @ NeurIPS 2026",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://wmhs-neurips.github.io/WMHS/"
  },
  {
    "id": "neurips2026_ws_WM_PAI",
    "name": "World Models in Physical AI Workshop",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "http://www.worldmodels-physicalai.com/"
  },
  {
    "id": "neurips2026_ws_XAI4Science",
    "name": "XAI4Science: Knowledge Discovery and Trust through Interpretable Foundation Models",
    "venue_type": "workshop",
    "venue_group": "NeurIPS 2026 Workshops",
    "track": "workshop",
    "deadline_label": "submission",
    "deadline_aoe": "2026-08-29 23:59:59",
    "notification_aoe": "2026-09-29 23:59:59",
    "link": "https://xai4science.github.io/"
  },
  {
    "id": "iclr2027_abstract",
    "name": "ICLR 2027 (abstract; paper Sep 24)",
    "venue_type": "conference",
    "venue_group": "ICLR 2027",
    "track": "main",
    "deadline_label": "abstract deadline",
    "deadline_aoe": "2026-09-19 23:59:59",
    "notification_aoe": "",
    "link": "https://iclr.cc/Conferences/2027"
  },
  {
    "id": "naacl2027_paper",
    "name": "NAACL 2027 (main, ARR submission)",
    "venue_type": "conference",
    "venue_group": "NAACL 2027",
    "track": "main",
    "deadline_label": "paper submission (ARR)",
    "deadline_aoe": "2026-10-12 23:59:59",
    "notification_aoe": "",
    "link": "https://2027.naacl.org/"
  }
];
