import { randomUUID } from "node:crypto";
import pg from "pg";
import { describe, expect, it } from "vitest";
import type { AdminBotMemberNotification } from "../contracts/actions.js";
import { AdminBotPostgresMemberNotifications } from "./postgres-member-notifications.js";
import { AdminBotSqliteStore } from "./sqlite.js";

const url = process.env.ADMINBOT_TEST_POSTGRES_URL;

describe.skipIf(!url)("PostgreSQL member notifications", () => {
  it("matches SQLite for member lists, escalations, updates, and deletion", async () => {
    const target = new URL(url!);
    if (!["localhost", "127.0.0.1", "[::1]"].includes(target.hostname)) {
      throw new Error("notification test requires local PostgreSQL");
    }
    const schema = `adminbot_migration_note_${randomUUID().replaceAll("-", "")}`;
    const pool = new pg.Pool({ connectionString: url, max: 2, connectionTimeoutMillis: 3000 });
    const sqlite = new AdminBotSqliteStore(":memory:");
    try {
      await pool.query(`CREATE SCHEMA "${schema}"`);
      await pool.query(`CREATE TABLE "${schema}".adminbot_member_notifications (
        _sqlite_rowid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
        id text PRIMARY KEY, member_id text NOT NULL, kind text NOT NULL,
        created_at text COLLATE "C" NOT NULL, read_at text, payload_json text NOT NULL
      )`);
      const postgres = new AdminBotPostgresMemberNotifications(pool, schema);
      const notification = (
        id: string,
        memberId: string,
        createdAt: string,
        escalatedAt?: string,
      ): AdminBotMemberNotification => ({
        id,
        member_id: memberId,
        kind: "nudge",
        title: `Reminder ${id}`,
        body: "Fictional test reminder",
        created_at: createdAt,
        ...(escalatedAt ? { escalated_at: escalatedAt } : {}),
      });
      const entries = [
        notification("old", "member-a", "2026-09-01T00:00:00Z", "2026-09-04T00:00:00Z"),
        notification("new", "member-a", "2026-09-03T00:00:00Z", "2026-09-03T00:00:00Z"),
        notification("other", "member-b", "2026-09-02T00:00:00Z"),
      ];
      for (const entry of entries) {
        sqlite.saveMemberNotification(entry);
        await postgres.saveMemberNotification(entry);
      }
      expect(await postgres.listMemberNotifications("member-a")).toEqual(
        sqlite.listMemberNotifications("member-a"),
      );
      expect(await postgres.listEscalatedMemberNotifications()).toEqual(
        sqlite.listEscalatedMemberNotifications(),
      );
      const read = { ...entries[1]!, read_at: "2026-09-05T00:00:00Z" };
      sqlite.saveMemberNotification(read);
      await postgres.saveMemberNotification(read);
      expect(await postgres.listEscalatedMemberNotifications()).toEqual(
        sqlite.listEscalatedMemberNotifications(),
      );
      expect(await postgres.deleteMemberNotification("old")).toBe(
        sqlite.deleteMemberNotification("old"),
      );
      expect(await postgres.deleteMemberNotification("old")).toBe(
        sqlite.deleteMemberNotification("old"),
      );
      expect(await postgres.listMemberNotifications("member-a")).toEqual(
        sqlite.listMemberNotifications("member-a"),
      );
      expect(await postgres.listMemberNotifications("member-b")).toEqual(
        sqlite.listMemberNotifications("member-b"),
      );
    } finally {
      sqlite.close();
      await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
      await pool.end();
    }
  });
});
