import { randomUUID } from "node:crypto";
import pg from "pg";
import { describe, expect, it } from "vitest";
import type { AdminBotAuditEvent } from "../contracts/actions.js";
import { AdminBotPostgresAuthStore } from "./postgres-auth.js";
import { AdminBotSqliteStore } from "./sqlite.js";

const url = process.env.ADMINBOT_TEST_POSTGRES_URL;

describe.skipIf(!url)("PostgreSQL audit retention", () => {
  it("matches SQLite's strict cutoff and retained event order", async () => {
    const target = new URL(url!);
    if (!["localhost", "127.0.0.1", "[::1]"].includes(target.hostname)) {
      throw new Error("audit retention test requires local PostgreSQL");
    }
    const schema = `adminbot_migration_audit_${randomUUID().replaceAll("-", "")}`;
    const pool = new pg.Pool({ connectionString: url, max: 2, connectionTimeoutMillis: 3000 });
    const sqlite = new AdminBotSqliteStore(":memory:");
    try {
      await pool.query(`CREATE SCHEMA "${schema}"`);
      await pool.query(`CREATE TABLE "${schema}".adminbot_audit_events (
        _sqlite_rowid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
        id text PRIMARY KEY, action_id text, event_type text NOT NULL,
        timestamp text COLLATE "C" NOT NULL, actor text, event_json text NOT NULL
      )`);
      const postgres = new AdminBotPostgresAuthStore(pool, schema);
      const events: AdminBotAuditEvent[] = [
        { id: "old", type: "proposal.created", timestamp: "2026-09-23T23:59:59.999Z" },
        { id: "boundary", type: "proposal.created", timestamp: "2026-09-24T00:00:00.000Z" },
        { id: "new", type: "proposal.created", timestamp: "2026-09-25T00:00:00.000Z" },
      ];
      for (const event of events) {
        sqlite.recordAudit(event);
        await postgres.recordAudit(event);
      }
      expect(await postgres.listAuditEvents()).toEqual(sqlite.listAuditEvents());
      const cutoff = "2026-09-24T00:00:00.000Z";
      expect(await postgres.pruneAuditEventsBefore(cutoff)).toBe(
        sqlite.pruneAuditEventsBefore(cutoff),
      );
      expect(await postgres.listAuditEvents()).toEqual(sqlite.listAuditEvents());
      expect((await postgres.listAuditEvents()).map((event) => event.id)).toEqual([
        "boundary",
        "new",
      ]);
      expect(await postgres.pruneAuditEventsBefore(cutoff)).toBe(
        sqlite.pruneAuditEventsBefore(cutoff),
      );
    } finally {
      sqlite.close();
      await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
      await pool.end();
    }
  });
});
