import { describe, expect, it } from "vitest";
import { parseVtt } from "./vtt.js";

const ZOOM_VTT = `WEBVTT

1
00:00:03.480 --> 00:00:06.140
Andrew Kim: Okay, let's get started.

2
00:00:06.200 --> 00:00:09.000
Andrew Kim: First item is the EMNLP deadline.

3
00:00:09.100 --> 00:00:12.500
Priya Raman: I pushed the ablations last night.

4
00:00:12.600 --> 00:00:14.000
[BLANK_AUDIO]
`;

describe("parseVtt", () => {
  it("reads cues, speakers and the recording length", () => {
    const transcript = parseVtt(ZOOM_VTT);
    expect(transcript.speakers).toEqual(["Andrew Kim", "Priya Raman"]);
    expect(transcript.cues).toHaveLength(4);
    expect(transcript.durationSeconds).toBe(14);
  });

  // The fold is what makes the text summarizable: Zoom cuts a cue every couple of seconds, so
  // without it the model is handed thousands of fragments that each re-state the speaker.
  it("folds consecutive cues from one speaker into a paragraph", () => {
    expect(parseVtt(ZOOM_VTT).text).toBe(
      "[00:00:03] Andrew Kim: Okay, let's get started. First item is the EMNLP deadline.\n\n" +
        "[00:00:09] Priya Raman: I pushed the ablations last night.\n\n" +
        "[00:00:12] [BLANK_AUDIO]",
    );
  });

  it("keeps speakers in the order they first spoke", () => {
    const transcript = parseVtt(`WEBVTT

1
00:00:01.000 --> 00:00:02.000
Zoe: hi

2
00:00:03.000 --> 00:00:04.000
Adam: hi

3
00:00:05.000 --> 00:00:06.000
Zoe: bye
`);
    expect(transcript.speakers).toEqual(["Zoe", "Adam"]);
  });

  // A sentence containing a colon is not a speaker label, and accepting one would put an invented
  // name on the attendance roster.
  it("does not read a sentence fragment as a speaker", () => {
    const transcript = parseVtt(`WEBVTT

1
00:00:01.000 --> 00:00:02.000
The link is here: https://example.com/paper

2
00:00:03.000 --> 00:00:04.000
one more thing before we wrap up here today: the retreat
`);
    expect(transcript.speakers).toEqual([]);
    expect(transcript.cues[0]?.text).toBe("The link is here: https://example.com/paper");
  });

  it("ignores headers and NOTE blocks", () => {
    const transcript = parseVtt(`WEBVTT

NOTE
This transcript was generated by Zoom.

1
00:00:01.000 --> 00:00:02.000
Ana: hello
`);
    expect(transcript.cues).toHaveLength(1);
    expect(transcript.speakers).toEqual(["Ana"]);
  });

  it("survives a truncated file rather than throwing on it", () => {
    expect(parseVtt("WEBVTT\n\n1\n00:00:01.000 --> ").cues).toEqual([]);
    expect(parseVtt("").speakers).toEqual([]);
  });

  it("handles a transcript that runs over an hour", () => {
    const transcript = parseVtt(`WEBVTT

1
01:02:03.000 --> 01:02:05.000
Ana: still going
`);
    expect(transcript.cues[0]?.startSeconds).toBe(3723);
    expect(transcript.text).toBe("[01:02:03] Ana: still going");
  });
});
