import { describe, expect, it, vi } from "vitest";
import type { AvailabilityPlanRecord, AvailabilityRepository, TransactionBoundary } from "@adminbot/ports";
import { AvailabilityWorkspaceService, type AvailabilityActor } from "./availability-workspace-service.js";

const ORG="10000000-0000-4000-8000-000000000001"; const PERSON="20000000-0000-4000-8000-000000000001"; const OTHER="20000000-0000-4000-8000-000000000002"; const PLAN="30000000-0000-4000-8000-000000000001"; const NOW=new Date("2026-08-08T12:00:00Z");
describe("AvailabilityWorkspaceService",()=>{
  it("summarizes current work and lets full time off override apparent capacity",async()=>{const fixture=harness([plan({entries:[entry("allocation",{hoursPerWeek:24}),entry("open_capacity",{id:"40000000-0000-4000-8000-000000000002",hoursPerWeek:8}),entry("time_off",{id:"40000000-0000-4000-8000-000000000003",timeOffAvailability:"none"})]})]);const result=await fixture.service.get(actor("member"));expect(result).toMatchObject({ok:true,body:{summaries:[{allocatedHours:0,openHours:0,away:"full",stale:false}]}});});
  it("redacts private reasons from member peers but exposes them to administrators",async()=>{const rows=[plan(),plan({id:"30000000-0000-4000-8000-000000000002",personId:OTHER,personName:"Other Member",entries:[entry("time_off",{privateReason:"private medical detail",timeOffAvailability:"partial"})]})];const member=await harness(rows).service.get(actor("member"));const admin=await harness(rows).service.get(actor("administrator"));if(!member.ok||!admin.ok)throw new Error("expected workspaces");expect(JSON.stringify(member.body.visiblePlans)).not.toContain("private medical detail");expect(JSON.stringify(admin.body.visiblePlans)).toContain("private medical detail");});
  it("replaces only the signed-in member plan with optimistic concurrency and audit",async()=>{const fixture=harness([plan()]);const input={planId:PLAN,expectedVersion:1,timeZone:"Europe/London",defaultWeeklyHours:35,entries:[clientEntry()]};const result=await fixture.service.replace(actor("member"),input);expect(result).toMatchObject({ok:true,body:{ownPlan:{version:2,timeZone:"Europe/London",defaultWeeklyHours:35}}});expect(fixture.audit).toHaveBeenCalledWith(expect.objectContaining({eventType:"availability.plan_replaced"}));await expect(fixture.service.replace(actor("member"),input)).resolves.toMatchObject({ok:false,status:409});});
  it("fails closed for non-members and invalid ranges",async()=>{const fixture=harness([plan()]);await expect(fixture.service.get(undefined)).resolves.toMatchObject({ok:false,status:401});await expect(fixture.service.get({...actor("member"),roles:["external_collaborator"]})).resolves.toMatchObject({ok:false,status:403});await expect(fixture.service.replace(actor("member"),{planId:PLAN,expectedVersion:1,timeZone:"UTC",defaultWeeklyHours:40,entries:[{...clientEntry(),startsOn:"2026-09-01",endsOn:"2026-08-01"}]})).resolves.toMatchObject({ok:false,status:400});});
  it("does not let ordinary plan replacement overwrite imported rows",async()=>{const imported=entry("allocation",{source:"imported",label:"Drive plan"});const fixture=harness([plan({entries:[imported]})]);await expect(fixture.service.replace(actor("member"),{planId:PLAN,expectedVersion:1,timeZone:"UTC",defaultWeeklyHours:40,entries:[]})).resolves.toMatchObject({ok:false,status:400,body:{message:expect.stringContaining("reconciliation")}});});
});
function harness(initial:AvailabilityPlanRecord[]){let rows=[...initial];const audit=vi.fn(async()=>undefined);const repository:AvailabilityRepository={listPeople:async()=>[...new Map(rows.map(r=>[r.personId,{personId:r.personId,personName:r.personName}])).values()],find:async(_o,p)=>rows.find(r=>r.personId===p),list:async()=>rows,ensure:async input=>{const made=plan({id:input.id,personId:input.personId,timeZone:input.timeZone,defaultWeeklyHours:input.defaultWeeklyHours,createdAt:input.now,updatedAt:input.now});rows.push(made);return made;},replace:async input=>{const current=rows.find(r=>r.id===input.id&&r.personId===input.personId);if(!current)return"not_found";if(current.version!==input.expectedVersion)return"conflict";const updated={...current,timeZone:input.timeZone,defaultWeeklyHours:input.defaultWeeklyHours,entries:input.entries.map(e=>({...e,planId:input.id})),version:current.version+1,updatedAt:input.now};rows=rows.map(r=>r.id===input.id?updated:r);return updated;}};const unit={availability:repository,audit:{append:audit},outbox:{enqueue:vi.fn(async()=>undefined)}};const transactions={read:async(fn:(u:typeof unit)=>Promise<unknown>)=>fn(unit),write:async(fn:(u:typeof unit)=>Promise<unknown>)=>fn(unit)} as unknown as TransactionBoundary;return{audit,service:new AvailabilityWorkspaceService({transactions,organizationId:ORG,now:()=>NOW,createId:()=>"50000000-0000-4000-8000-000000000001"})};}
function actor(role:"member"|"administrator"):AvailabilityActor{return{accountId:"60000000-0000-4000-8000-000000000001",organizationId:ORG,personId:PERSON,roles:[role]};}
function plan(overrides:Partial<AvailabilityPlanRecord>={}):AvailabilityPlanRecord{return{id:PLAN,organizationId:ORG,personId:PERSON,personName:"Member One",timeZone:"UTC",defaultWeeklyHours:40,entries:[entry("allocation",{hoursPerWeek:20,privateReason:"owner only"})],version:1,createdAt:NOW,updatedAt:NOW,...overrides};}
function entry(kind:"allocation"|"open_capacity"|"time_off"|"tentative",overrides:Partial<AvailabilityPlanRecord["entries"][number]>={}):AvailabilityPlanRecord["entries"][number]{return{id:"40000000-0000-4000-8000-000000000001",planId:PLAN,kind,startsOn:"2026-08-01",endsOn:"2026-08-31",visibility:"members",source:"manual",confirmedAt:NOW,...overrides};}
function clientEntry(){return{id:"40000000-0000-4000-8000-000000000004",kind:"allocation",startsOn:"2026-08-01",endsOn:"2026-09-01",hoursPerWeek:20,label:"Research",visibility:"members",source:"manual",confirmedAt:NOW.toISOString()};}
